using System.Net.Http.Json;
using System.Text.Json;
using MinecraftHarbor;
namespace HarborAgent;
public sealed record PackSyncLocalFile(string Path,string Hash,long Size,long WrittenUtcTicks);
public sealed record PackSyncState(string Host,string ServerId,string[] Files,PackSyncLocalFile[]? LocalFiles=null);
public sealed record PackSyncTransaction(string Backup,string[] Files,string[] Existed);
public sealed partial class ClientCore
{
    static readonly JsonSerializerOptions PackJson=new(JsonSerializerDefaults.Web){WriteIndented=true};
    public async Task<string> SyncPack(string folder,LanSyncInfo info,Action<string>? check=null)
    {
        check??=RequireGameClosed;check(folder);Recover(folder,check);
        Progress?.Invoke("Checking mod updates…");
        var profile=ClientProfile.Read(folder);if(info.ProjectId>0?profile.ProjectId!=info.ProjectId:!profile.Name.Equals(info.Pack,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("Choose an existing copy of "+info.Pack+" from the same modpack project.");
        using(var metadata=JsonDocument.Parse(File.ReadAllText(System.IO.Path.Combine(folder,"minecraftinstance.json")))){var j=metadata.RootElement;if(j.TryGetProperty("gameVersion",out var game)&&game.GetString()!=info.MinecraftVersion)throw new InvalidDataException("This server needs Minecraft "+info.MinecraftVersion+". Select the matching pack version in CurseForge.");if(j.TryGetProperty("baseModLoader",out var loader)&&loader.TryGetProperty("name",out var name)&&info.Loader.Length>0&&!name.GetString()!.StartsWith(info.Loader+"-",StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("This pack uses a different mod loader.");}
        using var response=await Post(Config.Host+"harbor/manifest",new PackSyncRequest(Config.Id,Config.Token,""));response.EnsureSuccessStatusCode();if(response.Content.Headers.ContentLength>32*1024*1024)throw new InvalidDataException("Pack manifest is too large.");var manifest=await response.Content.ReadFromJsonAsync<PackSyncManifest>()??throw new InvalidDataException("Missing pack manifest.");
        ValidateManifest(manifest);if(manifest.Hash!=info.ModHash||manifest.ProjectId!=info.ProjectId||manifest.MinecraftVersion!=info.MinecraftVersion||manifest.Loader!=info.Loader)throw new InvalidDataException("The server changed packs. Check for updates again.");
        string stateFile=System.IO.Path.Combine(folder,".harbor-sync-state.json");var previous=File.Exists(stateFile)?JsonSerializer.Deserialize<PackSyncState>(File.ReadAllText(stateFile),PackJson):null;if(previous!=null&&(previous.Host!=Config.Host||previous.ServerId!=manifest.ServerId))throw new InvalidDataException("This folder is synced to a different server. Choose a separate copy for this server.");
        var paths=manifest.Files.Select(f=>f.Path).ToHashSet(StringComparer.OrdinalIgnoreCase);
        var changes=await Task.Run(()=>{var existing=PackSyncPaths.Enumerate(folder).ToHashSet(StringComparer.OrdinalIgnoreCase);var cache=(previous?.LocalFiles??[]).ToDictionary(f=>f.Path,StringComparer.OrdinalIgnoreCase);return manifest.Files.Where(f=>{if(!existing.Contains(f.Path))return true;string target=System.IO.Path.Combine(folder,f.Path.Replace('/',System.IO.Path.DirectorySeparatorChar));var local=new FileInfo(target);if(local.Length!=f.Size)return true;if(cache.TryGetValue(f.Path,out var known)&&known.Hash==f.Hash&&known.Size==local.Length&&known.WrittenUtcTicks==local.LastWriteTimeUtc.Ticks)return false;return PackSyncPaths.HashFile(target)!=f.Hash;}).ToArray();});
        var removed=(previous?.Files??[]).Where(PackSyncPaths.Allowed).Concat(PackSyncPaths.Enumerate(folder).Where(p=>p.StartsWith("mods/",StringComparison.OrdinalIgnoreCase)&&p.EndsWith(".jar",StringComparison.OrdinalIgnoreCase))).Distinct(StringComparer.OrdinalIgnoreCase).Where(p=>!paths.Contains(p)&&File.Exists(PackSyncPaths.Resolve(folder,p))).ToArray();
        var nextState=new PackSyncState(Config.Host,manifest.ServerId,paths.ToArray(),manifest.Files.Select(f=>new PackSyncLocalFile(f.Path,f.Hash,f.Size,0)).ToArray());
        if(changes.Length==0&&removed.Length==0){SaveState(stateFile,nextState);return "Up to date";}
        string stage=System.IO.Path.Combine(folder,".harbor-sync-stage-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(stage);
        try{
            int index=0;foreach(var file in changes){Progress?.Invoke($"Downloading update {++index} of {changes.Length}…");using var deadline=new CancellationTokenSource(TimeSpan.FromMinutes(2));using var download=await Post(Config.Host+"harbor/file",new PackSyncRequest(Config.Id,Config.Token,manifest.Hash,file.Path));download.EnsureSuccessStatusCode();if(download.Content.Headers.ContentLength!=file.Size)throw new InvalidDataException("Downloaded file size changed: "+file.Path);string destination=PackSyncPaths.Resolve(stage,file.Path);Directory.CreateDirectory(System.IO.Path.GetDirectoryName(destination)!);using(var input=await download.Content.ReadAsStreamAsync())using(var output=File.Create(destination)){byte[] buffer=new byte[65536];long size=0;int count;while((count=await input.ReadAsync(buffer,deadline.Token))>0){size+=count;if(size>file.Size)throw new InvalidDataException("Update exceeds its published size.");await output.WriteAsync(buffer.AsMemory(0,count),deadline.Token);}if(size!=file.Size)throw new InvalidDataException("Download was incomplete.");}if(PackSyncPaths.HashFile(destination)!=file.Hash)throw new InvalidDataException("Update failed verification. Your pack has not been changed.");}
            check(folder);var latest=await Info();if(latest.ModHash!=manifest.Hash||!latest.FullPack)throw new InvalidDataException("The server changed during download. Check for updates again.");
            Progress?.Invoke("Saving local backups and applying the update…");await Task.Run(()=>CommitPack(folder,stage,changes.Select(f=>f.Path).ToArray(),removed,nextState,check));
            return $"Up to date · {changes.Length} updated, {removed.Length} removed";
        }finally{if(Directory.Exists(stage)){foreach(var file in Directory.EnumerateFiles(stage,"*",SearchOption.AllDirectories))File.Delete(file);foreach(var dir in Directory.EnumerateDirectories(stage,"*",SearchOption.AllDirectories).OrderByDescending(d=>d.Length))Directory.Delete(dir);Directory.Delete(stage);}}
    }
    internal static void ValidateManifest(PackSyncManifest m){if(m.Files==null||m.Files.Length>100000||m.Files.Sum(f=>f.Size)>16L*1024*1024*1024||m.Files.Any(f=>!PackSyncPaths.Allowed(f.Path)||f.Size<0||f.Size>512L*1024*1024||f.Hash.Length!=64||f.Hash.Any(c=>!Uri.IsHexDigit(c)))||m.Files.Select(f=>f.Path).Distinct(StringComparer.OrdinalIgnoreCase).Count()!=m.Files.Length||PackSyncPaths.HashList(m.Files)!=m.Hash)throw new InvalidDataException("Invalid pack manifest.");}
    static void SaveState(string file,PackSyncState state){string root=System.IO.Path.GetDirectoryName(file)!;if(state.LocalFiles!=null)state=state with{LocalFiles=state.LocalFiles.Select(f=>f with{WrittenUtcTicks=File.GetLastWriteTimeUtc(System.IO.Path.Combine(root,f.Path.Replace('/',System.IO.Path.DirectorySeparatorChar))).Ticks}).ToArray()};File.WriteAllText(file+".new",JsonSerializer.Serialize(state,PackJson));File.Move(file+".new",file,true);}
    internal static void CommitPack(string folder,string stage,string[] updated,string[] removed,PackSyncState state,Action<string> check)
    {
        check(folder);string backup=System.IO.Path.Combine(folder,"harbor-sync-backups",DateTime.Now.ToString("yyyyMMdd-HHmmss-fff")+"-"+Guid.NewGuid().ToString("N")[..8]);var affected=updated.Concat(removed).Distinct(StringComparer.OrdinalIgnoreCase).ToArray();var existed=affected.Where(p=>File.Exists(PackSyncPaths.Resolve(folder,p))).ToArray();Directory.CreateDirectory(backup);
        foreach(string path in existed){string source=PackSyncPaths.Resolve(folder,path),target=PackSyncPaths.Resolve(backup,path);Directory.CreateDirectory(System.IO.Path.GetDirectoryName(target)!);File.Copy(source,target);if(PackSyncPaths.HashFile(source)!=PackSyncPaths.HashFile(target))throw new IOException("Local backup verification failed.");}
        string journal=System.IO.Path.Combine(folder,".harbor-sync-transaction.json");File.WriteAllText(journal,JsonSerializer.Serialize(new PackSyncTransaction(backup,affected,existed),PackJson));
        try{foreach(string path in updated){check(folder);string target=PackSyncPaths.Resolve(folder,path);Directory.CreateDirectory(System.IO.Path.GetDirectoryName(target)!);File.Move(PackSyncPaths.Resolve(stage,path),target,true);}foreach(string path in removed){check(folder);File.Delete(PackSyncPaths.Resolve(folder,path));}check(folder);SaveState(System.IO.Path.Combine(folder,".harbor-sync-state.json"),state);File.Delete(journal);}
        catch{Restore(folder,new(backup,affected,existed));File.Delete(journal);throw;}
    }
    internal static void Recover(string folder,Action<string> check){string journal=System.IO.Path.Combine(folder,".harbor-sync-transaction.json");if(!File.Exists(journal))return;check(folder);var transaction=JsonSerializer.Deserialize<PackSyncTransaction>(File.ReadAllText(journal),PackJson)??throw new InvalidDataException("Invalid update recovery record.");Restore(folder,transaction);File.Delete(journal);}
    static void Restore(string folder,PackSyncTransaction t){string backupRoot=System.IO.Path.GetFullPath(System.IO.Path.Combine(folder,"harbor-sync-backups"))+System.IO.Path.DirectorySeparatorChar;if(!System.IO.Path.GetFullPath(t.Backup).StartsWith(backupRoot,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("Invalid backup recovery location.");foreach(string path in t.Files){string target=PackSyncPaths.Resolve(folder,path);if(t.Existed.Contains(path,StringComparer.OrdinalIgnoreCase)){string source=PackSyncPaths.Resolve(t.Backup,path);Directory.CreateDirectory(System.IO.Path.GetDirectoryName(target)!);File.Copy(source,target,true);}else if(File.Exists(target))File.Delete(target);}}
}


