using System.Net.Http.Json;
using System.Text.Json;
using MinecraftHarbor;
namespace HarborAgent;
public sealed record PackSyncLocalFile(string Path,string Hash,long Size,long WrittenUtcTicks);
public sealed record PackSyncState(string Host,string ServerId,string[] Files,PackSyncLocalFile[]? LocalFiles=null);
public sealed record PackSyncTransaction(string Backup,string[] Files,string[] Existed,string? LoaderBefore=null,string? LoaderAfter=null,string? CachePath=null,string? CacheBefore=null,string? CacheAfter=null);
public sealed partial class ClientCore
{
    static readonly JsonSerializerOptions PackJson=new(JsonSerializerDefaults.Web){WriteIndented=true};
    public async Task<string> SyncPack(string folder,LanSyncInfo info,Action<string>? check=null)
    {
        check??=RequireGameClosed;check(folder);await Task.Run(()=>Recover(folder,check,HarborUpdates.UpdateShutdown.CloseCurseForge));
        Progress?.Invoke("Checking mod updates…");
        var profile=ClientProfile.Read(folder);if(info.ProjectId>0?profile.ProjectId!=info.ProjectId:!profile.Name.Equals(info.Pack,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("Choose an existing copy of "+info.Pack+" from the same modpack project.");
        bool updateLoader=ReadLoaderVersion(folder,info,false)!=info.LoaderVersion||info.Loader=="neoforge"&&!NeoForgeUpdate.HasCurseForgeLaunchFiles(folder,info);
        if(updateLoader){if(info.Loader!="neoforge")RequireMatchingLoader(folder,info);Progress?.Invoke("Closing CurseForge…");await Task.Run(HarborUpdates.UpdateShutdown.CloseCurseForge);}
        using var response=await Post(Config.Host+"harbor/manifest",new PackSyncRequest(Config.Id,Config.Token,""));response.EnsureSuccessStatusCode();if(response.Content.Headers.ContentLength>32*1024*1024)throw new InvalidDataException("Pack manifest is too large.");var manifest=await response.Content.ReadFromJsonAsync<PackSyncManifest>()??throw new InvalidDataException("Missing pack manifest.");
        ValidateManifest(manifest);if(!SameServerVersion(info,manifest))throw new InvalidDataException("The server changed packs. Check for updates again.");
        string stateFile=System.IO.Path.Combine(folder,".harbor-sync-state.json");var previous=File.Exists(stateFile)?JsonSerializer.Deserialize<PackSyncState>(File.ReadAllText(stateFile),PackJson):null;if(previous!=null&&(previous.Host!=Config.Host||previous.ServerId!=manifest.ServerId))throw new InvalidDataException("This folder is synced to a different server. Choose a separate copy for this server.");
        var paths=manifest.Files.Select(f=>f.Path).ToHashSet(StringComparer.OrdinalIgnoreCase);
        var changes=await Task.Run(()=>{var existing=PackSyncPaths.Enumerate(folder).ToHashSet(StringComparer.OrdinalIgnoreCase);var cache=(previous?.LocalFiles??[]).ToDictionary(f=>f.Path,StringComparer.OrdinalIgnoreCase);return manifest.Files.Where(f=>{if(!existing.Contains(f.Path))return true;string target=System.IO.Path.Combine(folder,f.Path.Replace('/',System.IO.Path.DirectorySeparatorChar));var local=new FileInfo(target);if(local.Length!=f.Size)return true;if(cache.TryGetValue(f.Path,out var known)&&known.Hash==f.Hash&&known.Size==local.Length&&known.WrittenUtcTicks==local.LastWriteTimeUtc.Ticks)return false;return PackSyncPaths.HashFile(target)!=f.Hash;}).ToArray();});
        var removed=(previous?.Files??[]).Where(PackSyncPaths.Allowed).Concat(PackSyncPaths.Enumerate(folder).Where(p=>p.StartsWith("mods/",StringComparison.OrdinalIgnoreCase)&&p.EndsWith(".jar",StringComparison.OrdinalIgnoreCase))).Distinct(StringComparer.OrdinalIgnoreCase).Where(p=>!paths.Contains(p)&&File.Exists(PackSyncPaths.Resolve(folder,p))).ToArray();
        var nextState=new PackSyncState(Config.Host,manifest.ServerId,paths.ToArray(),manifest.Files.Select(f=>new PackSyncLocalFile(f.Path,f.Hash,f.Size,0)).ToArray());
        if(changes.Length==0&&removed.Length==0&&!updateLoader){SaveState(stateFile,nextState);return "Up to date";}
        string stage=System.IO.Path.Combine(folder,".harbor-sync-stage-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(stage);
        try{
            int index=0;foreach(var file in changes){Progress?.Invoke($"Downloading update {++index} of {changes.Length}…");using var deadline=new CancellationTokenSource(TimeSpan.FromMinutes(2));using var download=await Post(Config.Host+"harbor/file",new PackSyncRequest(Config.Id,Config.Token,manifest.Hash,file.Path));download.EnsureSuccessStatusCode();if(download.Content.Headers.ContentLength!=file.Size)throw new InvalidDataException("Downloaded file size changed: "+file.Path);string destination=PackSyncPaths.Resolve(stage,file.Path);Directory.CreateDirectory(System.IO.Path.GetDirectoryName(destination)!);using(var input=await download.Content.ReadAsStreamAsync())using(var output=File.Create(destination)){byte[] buffer=new byte[65536];long size=0;int count;while((count=await input.ReadAsync(buffer,deadline.Token))>0){size+=count;if(size>file.Size)throw new InvalidDataException("Update exceeds its published size.");await output.WriteAsync(buffer.AsMemory(0,count),deadline.Token);}if(size!=file.Size)throw new InvalidDataException("Download was incomplete.");}if(PackSyncPaths.HashFile(destination)!=file.Hash)throw new InvalidDataException("Update failed verification. Your pack has not been changed.");}
            LoaderProfileUpdate? loaderUpdate=updateLoader?await NeoForgeUpdate.Prepare(folder,info,Progress,check):null;
            check(folder);var latest=await Info();if(!SameServerVersion(latest,manifest)||!latest.FullPack)throw new InvalidDataException("The server changed during download. Check for updates again.");
            if(loaderUpdate==null)RequireMatchingLoader(folder,latest);Progress?.Invoke("Applying the update…");await Task.Run(()=>CommitPack(folder,stage,changes.Select(f=>f.Path).ToArray(),removed,nextState,check,loaderUpdate));
            RequireMatchingLoader(folder,latest);
            return $"Up to date · {changes.Length} updated, {removed.Length} removed"+(updateLoader?" · NeoForge "+info.LoaderVersion:"");
        }finally{if(Directory.Exists(stage)){foreach(var file in Directory.EnumerateFiles(stage,"*",SearchOption.AllDirectories))File.Delete(file);foreach(var dir in Directory.EnumerateDirectories(stage,"*",SearchOption.AllDirectories).OrderByDescending(d=>d.Length))Directory.Delete(dir);Directory.Delete(stage);}}
    }
    internal static void ValidateManifest(PackSyncManifest m){if(m.Files==null||m.Files.Length>100000||m.Files.Sum(f=>f.Size)>16L*1024*1024*1024||m.Files.Any(f=>!PackSyncPaths.Allowed(f.Path)||f.Size<0||f.Size>512L*1024*1024||f.Hash.Length!=64||f.Hash.Any(c=>!Uri.IsHexDigit(c)))||m.Files.Select(f=>f.Path).Distinct(StringComparer.OrdinalIgnoreCase).Count()!=m.Files.Length||PackSyncPaths.HashList(m.Files)!=m.Hash)throw new InvalidDataException("Invalid pack manifest.");}
    static void SaveState(string file,PackSyncState state){string root=System.IO.Path.GetDirectoryName(file)!;if(state.LocalFiles!=null)state=state with{LocalFiles=state.LocalFiles.Select(f=>f with{WrittenUtcTicks=File.GetLastWriteTimeUtc(System.IO.Path.Combine(root,f.Path.Replace('/',System.IO.Path.DirectorySeparatorChar))).Ticks}).ToArray()};File.WriteAllText(file+".new",JsonSerializer.Serialize(state,PackJson));File.Move(file+".new",file,true);}
    internal static void CommitPack(string folder,string stage,string[] updated,string[] removed,PackSyncState state,Action<string> check,LoaderProfileUpdate? loader=null,Action? launcherCheck=null)
    {
        check(folder);string backup=System.IO.Path.Combine(folder,".harbor-sync-recovery-"+Guid.NewGuid().ToString("N"));var affected=updated.Concat(removed).Distinct(StringComparer.OrdinalIgnoreCase).ToArray();var existed=affected.Where(p=>File.Exists(PackSyncPaths.Resolve(folder,p))).ToArray();string journal=System.IO.Path.Combine(folder,".harbor-sync-transaction.json");Directory.CreateDirectory(backup);try{
        foreach(string path in existed){string source=PackSyncPaths.Resolve(folder,path),target=PackSyncPaths.Resolve(backup,path);Directory.CreateDirectory(System.IO.Path.GetDirectoryName(target)!);File.Copy(source,target);if(PackSyncPaths.HashFile(source)!=PackSyncPaths.HashFile(target))throw new IOException("Local backup verification failed.");}
        launcherCheck??=NeoForgeUpdate.RequireLauncherClosed;string metadata=System.IO.Path.Combine(folder,"minecraftinstance.json");
        if(loader!=null){launcherCheck();if(File.ReadAllText(metadata)!=loader.Before)throw new InvalidOperationException("The profile changed during update. Try again.");File.WriteAllText(System.IO.Path.Combine(backup,"minecraftinstance.json"),loader.Before);}
        if(loader?.CachePath!=null){CurseForgeProfileCache.ValidatePath(loader.CachePath);if(File.ReadAllText(loader.CachePath)!=loader.CacheBefore)throw new InvalidOperationException("CurseForge's profile cache changed during the update. Try again.");File.WriteAllText(System.IO.Path.Combine(backup,"curseforge-profile-cache.json"),loader.CacheBefore);}
        var transaction=new PackSyncTransaction(backup,affected,existed,loader?.Before,loader?.After,loader?.CachePath,loader?.CacheBefore,loader?.CacheAfter);
        File.WriteAllText(journal,JsonSerializer.Serialize(transaction,PackJson));
        try{foreach(string path in updated){check(folder);string target=PackSyncPaths.Resolve(folder,path);Directory.CreateDirectory(System.IO.Path.GetDirectoryName(target)!);File.Move(PackSyncPaths.Resolve(stage,path),target,true);}foreach(string path in removed){check(folder);File.Delete(PackSyncPaths.Resolve(folder,path));}check(folder);if(loader!=null){launcherCheck();if(File.ReadAllText(metadata)!=loader.Before)throw new InvalidOperationException("The profile changed during update. Try again.");if(loader.CachePath!=null){if(File.ReadAllText(loader.CachePath)!=loader.CacheBefore)throw new InvalidOperationException("CurseForge's profile cache changed during update. Try again.");WriteLoaderMetadata(loader.CachePath,loader.CacheAfter!);}WriteLoaderMetadata(metadata,loader.After);check(folder);launcherCheck();}SaveState(System.IO.Path.Combine(folder,".harbor-sync-state.json"),state);File.Delete(journal);}
        catch{Restore(folder,transaction);File.Delete(journal);throw;}}finally{if(!File.Exists(journal)&&Directory.Exists(backup)){ValidateRecovery(folder,backup);Directory.Delete(backup,true);}}
    }
    internal static void Recover(string folder,Action<string> check,Action? launcherCheck=null){string journal=System.IO.Path.Combine(folder,".harbor-sync-transaction.json");if(!File.Exists(journal))return;check(folder);var transaction=JsonSerializer.Deserialize<PackSyncTransaction>(File.ReadAllText(journal),PackJson)??throw new InvalidDataException("Invalid update recovery record.");if(transaction.LoaderBefore!=null)(launcherCheck??NeoForgeUpdate.RequireLauncherClosed)();Restore(folder,transaction);File.Delete(journal);DeleteRecovery(folder,transaction);}
    static void ValidateRecovery(string folder,string path){string root=System.IO.Path.GetFullPath(folder),full=System.IO.Path.GetFullPath(path),legacy=System.IO.Path.Combine(root,"harbor-sync-backups")+System.IO.Path.DirectorySeparatorChar;bool temporary=string.Equals(System.IO.Path.GetDirectoryName(full),root,StringComparison.OrdinalIgnoreCase)&&System.Text.RegularExpressions.Regex.IsMatch(System.IO.Path.GetFileName(full),"^\\.harbor-sync-recovery-[a-f0-9]{32}$");if(!temporary&&!full.StartsWith(legacy,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("Invalid update recovery location.");}
    static void DeleteRecovery(string folder,PackSyncTransaction transaction){ValidateRecovery(folder,transaction.Backup);if(Directory.Exists(transaction.Backup))Directory.Delete(transaction.Backup,true);}
    static void WriteLoaderMetadata(string file,string contents){File.WriteAllText(file+".harbor-new",contents);File.Move(file+".harbor-new",file,true);}
    static void Restore(string folder,PackSyncTransaction t){ValidateRecovery(folder,t.Backup);if(t.CachePath!=null){CurseForgeProfileCache.ValidatePath(t.CachePath);if(t.CacheBefore==null||t.CacheAfter==null)throw new InvalidDataException("Incomplete CurseForge cache recovery record.");if(File.ReadAllText(t.CachePath)==t.CacheAfter)WriteLoaderMetadata(t.CachePath,t.CacheBefore);}if(t.LoaderBefore!=null){string metadata=System.IO.Path.Combine(folder,"minecraftinstance.json");if(File.ReadAllText(metadata)==t.LoaderAfter)WriteLoaderMetadata(metadata,t.LoaderBefore);}foreach(string path in t.Files){string target=PackSyncPaths.Resolve(folder,path);if(t.Existed.Contains(path,StringComparer.OrdinalIgnoreCase)){string source=PackSyncPaths.Resolve(t.Backup,path);Directory.CreateDirectory(System.IO.Path.GetDirectoryName(target)!);File.Copy(source,target,true);}else if(File.Exists(target))File.Delete(target);}}
}






