using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Text.Json;
using MinecraftHarbor;
namespace HarborAgent;
internal static class PackAgentTests
{
    internal static async Task Run(string report)
    {
        string root=System.IO.Path.Combine(System.IO.Path.GetDirectoryName(System.IO.Path.GetFullPath(report))!,"pack-agent-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);var checks=new List<string>();void Assert(bool value,string text){if(!value)throw new Exception(text);}
        string Profile(string label,long project=22){string folder=System.IO.Path.Combine(root,label);Directory.CreateDirectory(System.IO.Path.Combine(folder,"mods"));File.WriteAllText(System.IO.Path.Combine(folder,"minecraftinstance.json"),JsonSerializer.Serialize(new{guid=Guid.NewGuid().ToString(),gameVersion="1.20.1",baseModLoader=new{name="forge-47.4.0"},installedModpack=new{addonID=project,name="Factory Pack",authors=new[]{new{id=42}}}}));File.WriteAllText(System.IO.Path.Combine(folder,"mods/old.jar"),"old mod");Directory.CreateDirectory(System.IO.Path.Combine(folder,"saves/world"));File.WriteAllText(System.IO.Path.Combine(folder,"saves/world/level.dat"),"personal world");File.WriteAllText(System.IO.Path.Combine(folder,"options.txt"),"personal controls");return folder;}
        LoaderUpdateTests.CacheTransactions(root,checks);LoaderUpdateTests.Transactions(root,checks);UpdateTests.InstallFiles(root,checks);
        string selected=Profile("selected"),alternate=Profile("alternate"),different=Profile("different",99);
        string loaderFixture=Profile("loader-version-check");string loaderMetadata=System.IO.Path.Combine(loaderFixture,"minecraftinstance.json");
        void SetLoader(string game,string? loader){var json=System.Text.Json.Nodes.JsonNode.Parse(File.ReadAllText(loaderMetadata))!.AsObject();json["gameVersion"]=game;json["baseModLoader"]=loader==null?null:new System.Text.Json.Nodes.JsonObject{["name"]=loader};File.WriteAllText(loaderMetadata,json.ToJsonString());}
        var requiredLoader=new LanSyncInfo("Test","Factory Pack","1.21.1",true,"","","",22,"neoforge","21.1.249",true);
        SetLoader("1.21.1","neoforge-21.1.247");bool oldLoaderRejected=false;try{ClientCore.RequireMatchingLoader(loaderFixture,requiredLoader);}catch(InvalidDataException ex){oldLoaderRejected=ex.Message.Contains("21.1.247")&&ex.Message.Contains("21.1.249")&&ex.Message.Contains("CurseForge");}Assert(oldLoaderRejected,"Older NeoForge build was accepted or repair guidance is missing");
        SetLoader("1.21.1","neoforge-21.1.249");ClientCore.RequireMatchingLoader(loaderFixture,requiredLoader);
        foreach(var invalid in new[]{("1.21.1",(string?)null),("1.21.1","forge-21.1.249"),("1.20.1","neoforge-21.1.249"),("1.21.1","neoforge-")}){SetLoader(invalid.Item1,invalid.Item2);bool invalidRejected=false;try{ClientCore.RequireMatchingLoader(loaderFixture,requiredLoader);}catch(InvalidDataException){invalidRejected=true;}Assert(invalidRejected,"Incomplete or mismatching loader metadata was accepted");}
        SetLoader("1.20.1","forge-1.20.1-47.4.0");ClientCore.RequireMatchingLoader(loaderFixture,requiredLoader with{MinecraftVersion="1.20.1",Loader="forge",LoaderVersion="47.4.0"});
        SetLoader("1.21.1","fabric-0.16.14");ClientCore.RequireMatchingLoader(loaderFixture,requiredLoader with{Loader="fabric",LoaderVersion="0.16.14"});
        checks.Add("Exact NeoForge build is checked: 21.1.247 is rejected for 21.1.249 with repair guidance; matching NeoForge, Forge and Fabric builds are accepted; missing, wrong-game and wrong-loader metadata are rejected");
        Assert(ClientProfile.Read(selected).SamePack(ClientProfile.Read(alternate))&&!ClientProfile.Read(selected).SamePack(ClientProfile.Read(different)),"Alternate identity mismatch");Assert(ClientProfile.Read(alternate).LaunchUri.Contains("instanceId="+ClientProfile.Read(alternate).Guid),"Launch selects wrong instance");
        Directory.CreateDirectory(System.IO.Path.Combine(alternate,"config"));File.WriteAllText(System.IO.Path.Combine(alternate,"config/factory.toml"),"personal config");File.WriteAllText(System.IO.Path.Combine(alternate,"mods/readme.txt"),"keep me");
        var content=new Dictionary<string,byte[]>{{"mods/new.jar",Encoding.UTF8.GetBytes("new mod")},{"mods/extra.jar",Encoding.UTF8.GetBytes("extra mod")}};
        PackSyncManifest Manifest(){var files=content.Select(p=>new PackSyncFile(p.Key,Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(p.Value)),p.Value.Length)).ToArray();return new("test",22,"Factory Pack","1.20.1","forge","47.4.0",PackSyncPaths.HashList(files),files);}
        LanSyncInfo Info(){var m=Manifest();return new("Test","Factory Pack","1.20.1",true,"",m.Hash,m.Hash,22,"forge","47.4.0",true);}
        bool corrupt=false;var listener=new TcpListener(IPAddress.Loopback,0);listener.Start();using var cancel=new CancellationTokenSource();int port=((IPEndPoint)listener.LocalEndpoint).Port;
        var serving=Task.Run(async()=>{try{while(!cancel.IsCancellationRequested){using var socket=await listener.AcceptTcpClientAsync(cancel.Token);using var stream=socket.GetStream();byte[] input=new byte[8192];int length=0,split=-1;while(split<0){int n=await stream.ReadAsync(input.AsMemory(length),cancel.Token);if(n==0)break;length+=n;split=Encoding.UTF8.GetString(input,0,length).IndexOf("\r\n\r\n",StringComparison.Ordinal);}if(split<0)continue;string header=Encoding.UTF8.GetString(input,0,split);int.TryParse(header.Split("\r\n").FirstOrDefault(l=>l.StartsWith("Content-Length:"))?[15..].Trim(),out int bodyLength);while(length<split+4+bodyLength)length+=await stream.ReadAsync(input.AsMemory(length,split+4+bodyLength-length),cancel.Token);byte[] body;if(header.StartsWith("GET /harbor/info"))body=JsonSerializer.SerializeToUtf8Bytes(Info());else if(header.StartsWith("POST /harbor/manifest"))body=JsonSerializer.SerializeToUtf8Bytes(Manifest());else{var request=JsonSerializer.Deserialize<PackSyncRequest>(Encoding.UTF8.GetString(input,split+4,bodyLength))!;body=content[request.Path].ToArray();if(corrupt&&body.Length>0)body[0]^=1;}await stream.WriteAsync(Encoding.ASCII.GetBytes("HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: "+body.Length+"\r\nConnection: close\r\n\r\n"));await stream.WriteAsync(body);}}catch(OperationCanceledException){}});
        var cfg=new ClientConfig{Profile=selected,Host="http://127.0.0.1:"+port+"/",Token=new string('A',64)};using var client=new ClientCore(cfg);
        try{
            string originalMetadata=File.ReadAllText(System.IO.Path.Combine(selected,"minecraftinstance.json"));File.WriteAllText(System.IO.Path.Combine(selected,"minecraftinstance.json"),originalMetadata.Replace("forge-47.4.0","forge-47.3.0"));bool blocked=false;try{await client.Sync(selected,await client.Info(),_=>{});}catch(InvalidDataException ex){blocked=ex.Message.Contains("47.3.0");}Assert(blocked&&File.ReadAllText(System.IO.Path.Combine(selected,"mods/old.jar"))=="old mod"&&!Directory.Exists(System.IO.Path.Combine(selected,"harbor-sync-backups"))&&!File.Exists(System.IO.Path.Combine(selected,".harbor-sync-state.json")),"Wrong loader changed mods or claimed successful synchronization");File.WriteAllText(System.IO.Path.Combine(selected,"minecraftinstance.json"),originalMetadata);
            Assert(!ClientCore.SameServerVersion(Info() with{LoaderVersion="47.3.0"},Manifest()),"Loader change with identical mod hashes was missed");checks.Add("A loader mismatch stops the actual sync before changing any mods, backups or sync state; a host loader change invalidates an unchanged mod snapshot");
            await client.Sync(alternate,await client.Info(),_=>{});Assert(File.Exists(System.IO.Path.Combine(alternate,"mods/new.jar"))&&!File.Exists(System.IO.Path.Combine(alternate,"mods/old.jar")),"Added/removed mods not mirrored");Assert(content.All(p=>File.ReadAllBytes(PackSyncPaths.Resolve(alternate,p.Key)).SequenceEqual(p.Value)),"Pack content incomplete");Assert(cfg.Profile==selected&&File.ReadAllText(System.IO.Path.Combine(selected,"mods/old.jar"))=="old mod","One-time update changed selected pack");Assert(File.ReadAllText(System.IO.Path.Combine(alternate,"saves/world/level.dat"))=="personal world"&&File.ReadAllText(System.IO.Path.Combine(alternate,"options.txt"))=="personal controls","Personal files changed");Assert(File.ReadAllText(System.IO.Path.Combine(alternate,"config/factory.toml"))=="personal config"&&File.ReadAllText(System.IO.Path.Combine(alternate,"mods/readme.txt"))=="keep me","Non-mod files changed");checks.Add("Actual HTTP sync adds and removes mods and excludes Minecraft, configs, scripts, resources, and datapacks in another pack and game version; one-time copy preserves selected folder and personal files");
            content.Remove("mods/extra.jar");content["mods/new.jar"]=Encoding.UTF8.GetBytes("changed mod");await client.Sync(alternate,await client.Info(),_=>{});Assert(!File.Exists(PackSyncPaths.Resolve(alternate,"mods/extra.jar"))&&File.ReadAllText(PackSyncPaths.Resolve(alternate,"mods/new.jar"))=="changed mod","Changed/removed pack files not applied");Assert(Directory.GetFiles(System.IO.Path.Combine(alternate,"harbor-sync-backups"),"extra.jar",SearchOption.AllDirectories).Length>0,"Removed mod backup missing");
            Assert((await client.Sync(alternate,await client.Info(),_=>{}))=="Up to date","Unchanged cached pack redownloaded");var cached=JsonSerializer.Deserialize<PackSyncState>(File.ReadAllText(System.IO.Path.Combine(alternate,".harbor-sync-state.json")),new JsonSerializerOptions(JsonSerializerDefaults.Web));Assert(cached?.LocalFiles?.All(f=>f.WrittenUtcTicks>0)==true,"Quick-check file dates were not saved");File.WriteAllText(PackSyncPaths.Resolve(alternate,"mods/new.jar"),"tampered!!!");File.SetLastWriteTimeUtc(PackSyncPaths.Resolve(alternate,"mods/new.jar"),DateTime.UtcNow.AddMinutes(1));await client.Sync(alternate,await client.Info(),_=>{});Assert(File.ReadAllText(PackSyncPaths.Resolve(alternate,"mods/new.jar"))=="changed mod","Same-size local change was missed");checks.Add("Routine checks reuse saved file dates and sizes; a local change of the same size is detected and restored");
            bool rejected=false;try{await client.Sync(different,await client.Info(),_=>{});}catch(InvalidDataException){rejected=true;}Assert(rejected,"Different pack accepted");corrupt=true;rejected=false;try{await client.Sync(selected,await client.Info(),_=>{});}catch(InvalidDataException){rejected=true;}Assert(rejected&&File.ReadAllText(System.IO.Path.Combine(selected,"mods/old.jar"))=="old mod"&&!File.Exists(System.IO.Path.Combine(selected,"mods/new.jar")),"Corrupt download changed selected files");corrupt=false;
            content["mods/new.jar"]=Encoding.UTF8.GetBytes("third build");int count=0;rejected=false;try{await client.Sync(alternate,await client.Info(),_=>{if(++count==5)throw new InvalidOperationException("Game opened");});}catch(InvalidOperationException){rejected=true;}Assert(rejected&&File.ReadAllText(PackSyncPaths.Resolve(alternate,"mods/new.jar"))=="changed mod","Game-open failure did not roll back");checks.Add("Subsequent changes and removals apply with backups; wrong pack and corrupted download are rejected; mid-commit game launch rolls back");
            var m=Manifest();rejected=false;try{ClientCore.ValidateManifest(m with{Files=[new("mods/../../outside","A",1)]});}catch(InvalidDataException){rejected=true;}Assert(rejected&&!PackSyncPaths.Allowed("config/test.toml")&&!PackSyncPaths.Allowed("mods/readme.txt")&&!PackSyncPaths.Allowed("saves/world/level.dat"),"Unsafe path accepted");
            string recovery=System.IO.Path.Combine(alternate,"harbor-sync-backups/recovery");Directory.CreateDirectory(System.IO.Path.Combine(recovery,"mods"));File.WriteAllText(System.IO.Path.Combine(recovery,"mods/new.jar"),"recovered");File.WriteAllText(System.IO.Path.Combine(alternate,".harbor-sync-transaction.json"),JsonSerializer.Serialize(new PackSyncTransaction(recovery,["mods/new.jar"],["mods/new.jar"]),new JsonSerializerOptions(JsonSerializerDefaults.Web)));ClientCore.Recover(alternate,_=>{});Assert(File.ReadAllText(PackSyncPaths.Resolve(alternate,"mods/new.jar"))=="recovered","Interrupted update recovery failed");checks.Add("Path traversal and personal-world sync rejected; interrupted transaction restores previous content");
        }finally{cancel.Cancel();listener.Stop();await serving;}
        bool offline=false;try{await client.Info();}catch(HttpRequestException ex)when(ex.StatusCode==null){offline=true;}Assert(offline,"Offline condition missing");checks.Add("Offline launch condition detected");File.WriteAllText(report,JsonSerializer.Serialize(new{passed=true,checks,realClientTouched=false},new JsonSerializerOptions{WriteIndented=true}));
    }
}


