<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Minecraft-Harbor-Client-Setup</AssemblyName>
    <ApplicationIcon>../source/harbor.ico</ApplicationIcon>
    <ApplicationManifest>../source/app.manifest</ApplicationManifest>
    <Version>1.0.0</Version>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../client-setup/automodpack-mc1.21.1-neoforge-4.0.6.jar" LogicalName="Harbor.SyncHelper.jar" />
    <PackageReference Include="System.Management" Version="10.0.0" />
  </ItemGroup>
</Project>
