using System.Diagnostics;

namespace MinecraftHarbor;
internal static class AppSettingsTests
{
    internal static void Run(string report,bool demo=false)
    {
        report=Path.GetFullPath(report);Directory.CreateDirectory(Path.GetDirectoryName(report)!);string root=Path.Combine(Path.GetDirectoryName(report)!,"settings-fixture-"+Guid.NewGuid().ToString("N"));PlayerTests.Fixture(root,3);
        ServerManager.WriteJson(Path.Combine(root,"appearance.json"),new AppearanceSettings());
        ProcessStartInfo Launcher(){var info=new ProcessStartInfo(Environment.ProcessPath!);info.ArgumentList.Add("--mock-server");return info;}
        using var manager=new ServerManager(root,Launcher);using var form=new MainForm(manager,visualTestReport:demo?"__app_settings_demo__":"__app_settings_test__:"+report);Application.Run(form);
    }
}
public sealed partial class MainForm
{
    internal async Task VerifyAppSettings(string report)
    {
        var checks=new List<string>();void Assert(bool value,string message){if(!value)throw new Exception(message);}async Task Until(Func<bool> value){var watch=Stopwatch.StartNew();while(!value()){if(watch.Elapsed.TotalSeconds>12)throw new TimeoutException("Settings test timed out");await Task.Delay(20);}}
        void Capture(string name){using var image=new Bitmap(Width,Height);DrawToBitmap(image,new Rectangle(Point.Empty,Size));image.Save(Path.Combine(Path.GetDirectoryName(report)!,name+".png"));}
        try{
            playerImagesDisabled=true;ShowPage("Backups");var firstBackupBounds=backupTable.Bounds;var firstBackupPage=pages["Backups"].Bounds;Assert(pageEntrance==null||pageEntrance.Bounds==firstBackupPage,"First Backups cover uses stale page bounds");if(MotionEnabled){Assert(pageEntrance!=null,"Backups entrance did not start");await Task.Delay(100);Assert(pageEntrance!=null&&pageEntrance.Alpha>0&&pageEntrance.Alpha<1,"Backups did not fade progressively");}await Until(()=>pageEntrance==null);
            ShowPage("Players");if(MotionEnabled)Assert(pageEntrance!=null,"Players entrance did not start");ShowPage("Home");Assert(pageEntrance==null,"Leaving Players retained its cover");ShowPage("Backups");ShowPage("Players");ShowPage("Settings");await Until(()=>pageEntrance==null);ShowPage("Backups");ClientSize=new Size(LogicalToDeviceUnits(1160),LogicalToDeviceUnits(680));Assert(pageEntrance==null,"Resizing retained a stale cover");checks.Add("Backups and Players fade progressively; rapid navigation, leaving, and resizing clean up the cover");
            for(int pc=0;pc<3;pc++){string id=Guid.NewGuid().ToString();string token=setup.Pcs.Pair(new(setup.Pcs.NewCode(),id,new[]{"Desktop","Living Room","Laptop"}[pc]),"192.168.1."+(101+pc)).Token;setup.Pcs.Heartbeat(new(id,token,setup.Info().ModHash,pc==0,"Connected"),"192.168.1."+(101+pc));}
            foreach(var size in new[]{new Size(1320,744),new Size(1160,680)}){ClientSize=new Size(LogicalToDeviceUnits(size.Width),LogicalToDeviceUnits(size.Height));ShowPage("Settings");await Until(()=>pageEntrance==null);foreach(string category in new[]{"Appearance","Behavior","Console","Notifications","Tools"}){settingsCategory=category;RenderAppSettings();Assert(!pages["Settings"].AutoScroll&&pages["Settings"].AutoScrollPosition==Point.Empty,"Settings still scrolls");Assert(settingsCard.Controls.Cast<Control>().All(c=>c.Left>=0&&c.Right<=settingsCard.Width+2&&c.Bottom<=settingsCard.Height),"Setting control clipped");Assert(category=="Tools"?!appSave.Visible:appCancel.Right<appSave.Left&&appSave.Right<=settingsCard.Width&&settingsCard.Bottom<appSave.Top&&appSave.Bottom<=pages["Settings"].ClientSize.Height,"Setting actions overlap or clip");Capture("settings-"+category.ToLowerInvariant()+"-"+size.Width);}ShowPage("LAN PCs");await Until(()=>pageEntrance==null);Assert(lanAddress.Bottom<=pages["LAN PCs"].Height&&lanHelp.Bottom<=pages["LAN PCs"].Height&&lanDownload.Bottom<=lanAddress.Top,"LAN cards clip or overlap");Assert(lanHelp.Controls.OfType<HarborButton>().All(b=>b.Bottom<=lanHelp.Height),"LAN help buttons clipped");Assert(lanRows.Controls.OfType<PaintedPanel>().Count()==3,"Paired PC rows missing");Capture("lan-pcs-"+size.Width);}ShowPage("Settings");await Until(()=>pageEntrance==null);settingsCategory="Appearance";RenderAppSettings();checks.Add("Five Settings categories fit with no scrolling; LAN PCs cards and controls fit both supported window sizes");
            await server.StartAsync();await Until(()=>server.State==ServerState.Running);string process=File.ReadAllText(Path.Combine(server.Root,"server-process.json")),config=File.ReadAllText(Path.Combine(server.Root,"settings.json"));
            settingsDraft.ConsoleFontSize=14;settingsDraft.ConsoleFollow=false;settingsDraft.ConsoleHistoryCharacters=100000;settingsDraft.Animations=false;settingsDraft.RememberPage=true;settingsDraft.KeepAwake=false;settingsDraft.NotifyBackups=true;appSave.PerformClick();await Until(()=>File.Exists(Path.Combine(server.Root,"app-settings.json")));var saved=AppPreferences.Load(server.Root);Assert(saved.ConsoleFontSize==14&&!saved.Animations&&saved.NotifyBackups&&!saved.KeepAwake,"Preferences did not persist");Assert(Math.Abs(console.TextBox.Font.SizeInPoints-14)<.1&&!console.TextBox.FollowMessages&&console.TextBox.HistoryCharacters==100000,"Console changes did not apply live");Assert(File.ReadAllText(Path.Combine(server.Root,"server-process.json"))==process&&File.ReadAllText(Path.Combine(server.Root,"settings.json"))==config&&server.State==ServerState.Running,"App preferences modified or restarted the server");
            settingsDraft.ConsoleFontSize=9;appCancel.PerformClick();Assert(settingsDraft.ConsoleFontSize==14&&preferences.ConsoleFontSize==14,"Cancel did not discard pending changes");applicationShown=true;ShowPage("Console");Assert(AppPreferences.Load(server.Root).LastPage=="Console","Last-tab preference did not persist navigation");ShowPage("Backups");Assert(pageEntrance==null,"Disabled animations still created a fade");checks.Add("Preferences save and cancel correctly, console options apply live, last-tab history persists, and reduced motion removes transitions without restarting or changing the server");
            string clampRoot=Path.Combine(server.Root,"clamp");Directory.CreateDirectory(clampRoot);var bad=new AppPreferences{FadeMilliseconds=9000,ConsoleFontSize=100,ConsoleHistoryCharacters=5};bad.Save(clampRoot);var normalized=AppPreferences.Load(clampRoot);Assert(normalized.FadeMilliseconds==1000&&normalized.ConsoleFontSize==16&&normalized.ConsoleHistoryCharacters==100000,"Invalid preferences not bounded");
            await server.StopAsync();ServerManager.WriteJson(report,new{passed=true,checks,realServerTouched=false});
        }catch(Exception ex){ServerManager.WriteJson(report,new{passed=false,error=ex.ToString(),checks,realServerTouched=false});}finally{if(server.HasProcess)await server.StopAsync();exiting=true;Close();}
    }
}

