using System.Text.Json;
namespace MinecraftHarbor;
internal static class AutoModpackTests
{
    internal static void Run(string report,string helper)
    {
        string root=Path.Combine(Path.GetDirectoryName(Path.GetFullPath(report))!,"connector-fixture-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);
        string client=Path.Combine(root,"Client"),server=Path.Combine(root,"server"),setup=Path.Combine(root,"client-setup");Directory.CreateDirectory(client);Directory.CreateDirectory(server);Directory.CreateDirectory(setup);
        void Metadata(int file,int serverFile)=>File.WriteAllText(Path.Combine(client,"minecraftinstance.json"),JsonSerializer.Serialize(new{name="Renamed profile",gameVersion="1.21.1",baseModLoader=new{name="neoforge-21.1.249"},installedModpack=new{addonID=925200,name="ATM10",installedFile=new{id=file,fileName="ATM10-8.1.zip",serverPackFileId=serverFile}}}));
        void Check(bool result,string message){if(!result)throw new Exception(message);}
        Metadata(8764211,8764245);File.WriteAllText(Path.Combine(client,"manifest.json"),"{\"version\":\"8.1\"}");
        var installed=CurseForgeProfiles.Read(client);Check(installed.ClientFileId==8764211,"Installed release ID wasn't read");
        var profile=new ServerProfile{JavaPath=Environment.GetEnvironmentVariable("HARBOR_TEST_JAVA")??throw new Exception("Set HARBOR_TEST_JAVA to Java 21 for this integration test."),Name="ATM10",PackVersion="8.1",ProjectId=925200,ServerFileId=8764245,CurseForgePath=client,Loader="neoforge",MinecraftVersion="1.21.1"};
        string initial=JsonSerializer.Serialize(AutoModpackSetup.Requirement(profile));Check(profile.CurseForgeClientFileId==8764211&&initial.Contains("8764211"),"Required release wasn't pinned");
        Metadata(999,111);Check(JsonSerializer.Serialize(AutoModpackSetup.Requirement(profile))==initial,"Updating the host client silently changed the server's required release");
        string tools=Path.Combine(root,"server-tools");Directory.CreateDirectory(tools);foreach(var file in Directory.GetFiles(Path.Combine(AppContext.BaseDirectory,"server-tools")))File.Copy(file,Path.Combine(tools,Path.GetFileName(file)));File.Copy(helper,Path.Combine(setup,ClientSetup.HelperName));Directory.CreateDirectory(Path.Combine(server,"mods"));File.WriteAllText(Path.Combine(server,"mods","automodpack-mc1.21.1-neoforge-4.0.6-harbor14.jar"),"retired fork");File.WriteAllText(Path.Combine(server,"mods","custom.jar"),"custom mod");
        Directory.CreateDirectory(Path.Combine(server,"automodpack",".private"));string cert=Path.Combine(server,"automodpack",".private","cert.crt");File.WriteAllText(cert,"existing certificate");File.WriteAllText(Path.Combine(server,"automodpack",".private","key.pem"),"existing private key fixture");Directory.CreateDirectory(Path.Combine(server,"automodpack","host-modpack"));File.WriteAllText(Path.Combine(server,"automodpack","host-modpack","patch-notes.md"),"Operator notes remain.");
        File.WriteAllText(Path.Combine(server,"automodpack","automodpack-server.json"),"{\"syncedFiles\":[\"/mods/*.jar\",\"/kubejs/**\"],\"allowEditsInFiles\":[\"/options.txt\",\"/config/**\"],\"bindPort\":25567}");
        File.WriteAllText(Path.Combine(server,"automodpack","harbor-requirements.json"),initial);
        AutoModpackSetup.Prepare(root,server,profile);AutoModpackSetup.Prepare(root,server,profile);
        string inspection=Path.Combine(root,"inspection.json");AutoModpackSetup.Configure(root,server,profile,"--inspect",inspection);using var config=JsonDocument.Parse(File.ReadAllText(inspection));var settings=config.RootElement;var main=settings.GetProperty("modpack").GetProperty("General").GetProperty("main");
        Check(main.GetProperty("from-server").EnumerateArray().Any(x=>x.GetString()=="config/**"),"Configs aren't synchronized");Check(!main.GetProperty("editable").EnumerateArray().Any(x=>x.GetString()=="config/**"),"Config updates disabled");Check(settings.GetProperty("bind-port").GetInt32()==25567,"Network configuration changed");
        Check(File.ReadAllText(cert)=="existing certificate"&&File.ReadAllText(Path.Combine(server,"mods","custom.jar"))=="custom mod","Certificate or custom mod changed");Check(Directory.GetFiles(Path.Combine(server,"mods"),"automodpack*.jar").Length==1,"Duplicate helper installed");
        Check(JsonSerializer.Serialize(AutoModpackSetup.Requirement(new(){Loader="vanilla"}))=="null","Vanilla got a CurseForge requirement");
        Check(!File.Exists(Path.Combine(server,"automodpack","harbor-requirements.json")),"Retired enforced requirement wasn't removed");
        Check(File.ReadAllBytes(Path.Combine(server,"mods",ClientSetup.HelperName)).SequenceEqual(File.ReadAllBytes(helper)),"Server received modified AutoModpack bytes");
        // A missing/mismatched host client profile must not gate official AutoModpack setup.
        File.Delete(Path.Combine(client,"minecraftinstance.json"));profile.CurseForgeClientFileId=0;AutoModpackSetup.Prepare(root,server,profile);
        Check(main.GetProperty("display-name").GetString()!.Contains("ATM10 8.1"),"Native confirmation reminder missing");string notes=File.ReadAllText(Path.Combine(server,"automodpack","host-modpack","patch-notes.md"));Check(notes.Contains("Operator notes remain.")&&notes.Split("<!-- Harbor pack reminder -->").Length==2,"Update notes were lost or reminder duplicated");Check(File.ReadAllText(Path.Combine(server,"automodpack","credentials","certificate.crt"))=="existing certificate","Certificate migration changed identity");File.AppendAllText(Path.Combine(server,"automodpack","server.conf"),"\n# Operator comment remains\n");profile.PackVersion="8.2";AutoModpackSetup.Prepare(root,server,profile);Check(File.ReadAllText(Path.Combine(server,"automodpack","server.conf")).Contains("Operator comment remains"),"Operator comments lost");AutoModpackSetup.Configure(root,server,profile,"--inspect",inspection);using var updated=JsonDocument.Parse(File.ReadAllText(inspection));Check(updated.RootElement.GetProperty("modpack").GetProperty("General").GetProperty("main").GetProperty("display-name").GetString()!.Contains("8.2"),"Reminder did not follow server pack release");ServerManager.WriteJson(report,new{passed=true,checks=new[]{"Server pack metadata retained","Configs sync and update; user settings excluded","Official AutoModpack installed byte-for-byte and retired fork removed","Version enforcement removed; setup works without client metadata","Repeated setup preserves certificate, custom mods and network settings"},realServerTouched=false});
    }
}
