using System.Diagnostics;
using System.IO.Compression;

namespace MinecraftHarbor;
internal static class BackupUiTests
{
    public static void Run(string report,bool demo=false)
    {
        report=Path.GetFullPath(report);Directory.CreateDirectory(Path.GetDirectoryName(report)!);var root=Path.Combine(Path.GetDirectoryName(report)!,"backups-ui-fixture-"+Guid.NewGuid().ToString("N"));LibraryTests.WriteWorld(Path.Combine(root,"server","world"));
        File.WriteAllText(Path.Combine(root,"server","eula.txt"),"eula=true");ServerManager.WriteJson(Path.Combine(root,"settings.json"),new Settings{MemoryGB=8,WorldName="Backup test world"});ServerManager.WriteJson(Path.Combine(root,"appearance.json"),new AppearanceSettings());
        ProcessStartInfo Launcher(){var info=new ProcessStartInfo(Environment.ProcessPath!);info.ArgumentList.Add("--mock-server");return info;}
        using var manager=new ServerManager(root,Launcher);manager.Profile.ServerName="My Test Server";
        for(int i=0;i<15;i++){var file=Path.Combine(manager.BackupDir,i==14?"original-singleplayer.zip":$"test-{i}.zip");using var zip=ZipFile.Open(file,ZipArchiveMode.Create);zip.CreateEntryFromFile(Path.Combine(manager.WorldDir,"level.dat"),"world/level.dat");using var writer=new StreamWriter(zip.CreateEntry("harbor-backup.json").Open());writer.Write(System.Text.Json.JsonSerializer.Serialize(new{createdUtc=DateTime.UtcNow.AddMinutes(-i),reason=i%2==0?"manual":"hourly",profileId=manager.Profile.Id,worldFolder=manager.Config.WorldFolder}));}
        File.WriteAllText(Path.Combine(manager.BackupDir,"broken.zip"),"not a zip");using var form=new MainForm(manager,backupTestReport:demo?"__backups_demo__":report);Application.Run(form);
    }
}
public sealed partial class MainForm
{
    internal async Task VerifyBackupDesign(string report)
    {
        var checks=new List<string>();void Assert(bool pass,string message){if(!pass)throw new Exception(message);}
        void Capture(string name){using var image=new Bitmap(Width,Height);DrawToBitmap(image,new Rectangle(Point.Empty,Size));image.Save(Path.Combine(Path.GetDirectoryName(report)!,name+".png"));}
        try{
            ShowPage("Backups");await Task.Delay(350);RefreshBackups();Assert(backupEntries.Count==16,"Backup list is incomplete");Assert(backupEntries.Count(e=>e.Kind=="Automatic")==7,"Automatic metadata was not read");Assert(backupEntries.Single(e=>Path.GetFileName(e.File)=="broken.zip").Restorable==false,"Unreadable backup is restorable");
            foreach(var size in new[]{new Size(1320,744),new Size(1160,680)}){ClientSize=new Size(LogicalToDeviceUnits(size.Width),LogicalToDeviceUnits(size.Height));await Task.Delay(100);Assert(backupTable.Bottom<backupTotals.Top&&backupTotals.Bottom<=pages["Backups"].Height,"Table or totals are clipped");foreach(var row in backupRows.Controls.OfType<PaintedPanel>()){var buttons=row.Controls.OfType<HarborButton>().ToArray();Assert(buttons.All(b=>b.Left>=0&&b.Right<=row.Width)&&buttons.Zip(buttons.Skip(1)).All(p=>p.First.Right<p.Second.Left),"Backup actions overlap");foreach(var action in buttons.Where(b=>b.Text is "Restore" or "Download")){int label=TextRenderer.MeasureText(action.Text,action.Font,new Size(int.MaxValue,int.MaxValue),TextFormatFlags.SingleLine|TextFormatFlags.NoPrefix|TextFormatFlags.NoPadding).Width;Assert(label+2<=action.Width-action.LogicalToDeviceUnits(61),"Action text is clipped: "+action.Text);}}Capture(size.Width==1320?"backups-list":"backups-list-small");}
            Assert(backupRows.AutoScrollMinSize.Height>backupRows.Height&&backupRows.Controls.OfType<BackupScrollRail>().Any(c=>!c.IsDisposed),"Long backup list is not scrollable");backupRows.AutoScrollPosition=new Point(0,backupRows.AutoScrollMinSize.Height);Assert(backupRows.AutoScrollPosition.Y<0,"Backup list did not scroll");backupSearch.Text="Hourly";Assert(backupRows.Controls.OfType<PaintedPanel>().Count()==7,"Search did not filter descriptions");backupSearch.Text="does not exist";Assert(!backupRows.Controls.OfType<PaintedPanel>().Any(),"Empty search shows old rows");backupSearch.Clear();checks.Add("Complete list, automatic labels, readable archive checks, search, scrolling, and actions at both supported window sizes");
            var manual=backupEntries.First(e=>e.Kind=="Manual"&&e.Restorable);backupCatalog.Rename(server.BackupDir,manual,"Pre-Update Backup","Before updating mods");RefreshBackups();Assert(backupEntries.Single(e=>e.File==manual.File).Name=="Pre-Update Backup","Custom name did not persist");var reopened=new BackupCatalog().Read(server.BackupDir);Assert(reopened.Single(e=>e.File==manual.File).Description=="Before updating mods","Custom note did not persist");
            var export=Path.Combine(server.Root,"exported.zip");BackupCatalog.Export(server.BackupDir,manual,export);Assert(File.ReadAllBytes(export).SequenceEqual(File.ReadAllBytes(manual.File)),"Export changed archive content");var original=backupEntries.Single(e=>e.Protected);bool rejected=false;try{backupCatalog.Delete(server.BackupDir,original);}catch(InvalidOperationException){rejected=true;}Assert(rejected&&File.Exists(original.File),"Protected original could be deleted");rejected=false;try{backupCatalog.Delete(Path.Combine(server.Root,"other"),manual);}catch(IOException){rejected=true;}Assert(rejected,"Action accepted a backup from a different folder");backupCatalog.Delete(server.BackupDir,manual);Assert(!File.Exists(manual.File)&&!File.Exists(manual.File+".label.json"),"Delete did not remove backup and label");RefreshBackups();checks.Add("Name and note persist without changing ZIP; export preserves bytes; original and other server folders are protected; deleting a disposable backup works");
            SelectBackupTab(true);Assert(backupSchedule.Visible&&!backupTable.Visible&&!backupSearchFrame.Visible&&backupSchedule.Bottom<backupTotals.Top,"Automatic settings tab did not switch or overlaps totals");Capture("backups-automatic");SelectBackupTab(false);
            await server.StartAsync();var watch=Stopwatch.StartNew();while(server.State==ServerState.Starting&&watch.Elapsed.TotalSeconds<15)await Task.Delay(20);Assert(server.State==ServerState.Running,"Fixture failed startup");RefreshBackupStatus();Assert(backupRestoreButtons.All(e=>!e.Button.Enabled)&&createBackupButton.Enabled,"Restore enabled while online or manual backup disabled");string process=File.ReadAllText(Path.Combine(server.Root,"server-process.json"));int count=Directory.GetFiles(server.BackupDir,"*.zip").Length;server.SetAutomaticBackups(false);Assert(server.NextAutomaticBackupUtc==null&&!server.Config.AutomaticBackups,"Disabling automatic backups failed");server.SetAutomaticBackups(true);Assert(server.NextAutomaticBackupUtc>DateTime.UtcNow.AddMinutes(59)&&server.Config.AutomaticBackups,"Enabling did not schedule next hour");Assert(File.ReadAllText(Path.Combine(server.Root,"server-process.json"))==process&&Directory.GetFiles(server.BackupDir,"*.zip").Length==count,"Backup preferences restarted server or created backup");await server.StopAsync();RefreshBackupStatus();Assert(backupRestoreButtons.Where(e=>e.Entry.Restorable).All(e=>e.Button.Enabled),"Restore did not return after stopping");checks.Add("Hourly settings apply live without stopping or creating archives; restore is gated while online; original retention and world archive format remain unchanged");
            ClientSize=new Size(1320,744);ServerManager.WriteJson(report,new{passed=true,checks,realServerTouched=false});
        }catch(Exception ex){ServerManager.WriteJson(report,new{passed=false,error=ex.ToString(),checks,realServerTouched=false});}
        finally{if(server.HasProcess)await server.StopAsync();exiting=true;Close();}
    }
}
