using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
namespace MinecraftHarbor;
internal static class LanTests
{
    internal static async Task Run(string report)
    {
        report=Path.GetFullPath(report);Directory.CreateDirectory(Path.GetDirectoryName(report)!);string root=Path.Combine(Path.GetDirectoryName(report)!,"lan-fixture-"+Guid.NewGuid().ToString("N"));PlayerTests.Fixture(root,2);Directory.CreateDirectory(Path.Combine(root,"server","mods"));File.WriteAllText(Path.Combine(root,"server","mods","ftb-ultimine-neoforge-2101.1.15.jar"),"test-mod");using var manager=new ServerManager(root);manager.Profile.CustomUltimineSync=true;using var setup=new ClientSetup(root,()=>manager,0);setup.Start();using var http=new HttpClient{BaseAddress=new("http://127.0.0.1:"+setup.ListeningPort+"/"),Timeout=TimeSpan.FromSeconds(5)};var checks=new List<string>();void Assert(bool condition,string error){if(!condition)throw new Exception(error);}
        async Task<HttpResponseMessage> Post<T>(string uri,T value){using var content=new StringContent(JsonSerializer.Serialize(value),Encoding.UTF8,"application/json");return await http.PostAsync(uri,content);}
        var info=await http.GetFromJsonAsync<LanSyncInfo>("harbor/info");Assert(info?.ModHash.Length==64,"Missing server update metadata");string id=Guid.NewGuid().ToString(),code=setup.Pcs.NewCode();using var bad=await Post("harbor/pair",new LanPairRequest("000000",id,"Test PC"));Assert((int)bad.StatusCode==403,"Invalid pairing accepted");using var valid=await Post("harbor/pair",new LanPairRequest(code,id,"Test PC"));valid.EnsureSuccessStatusCode();var token=(await valid.Content.ReadFromJsonAsync<LanPairResponse>())!.Token;Assert(token.Length==64&&setup.Pcs.Snapshot().Count==1,"Pairing failed");using var reused=await Post("harbor/pair",new LanPairRequest(code,Guid.NewGuid().ToString(),"Other PC"));Assert((int)reused.StatusCode==403,"Pairing code reusable");checks.Add("Live local HTTP pairing rejects invalid and reused codes and stores a token hash, never the raw token");Assert(!File.ReadAllText(Path.Combine(root,"lan-pcs.json")).Contains(token),"Raw token saved on host");
        var status=new LanHeartbeat(id,token,info!.ModHash,false,"Up to date");using var heartbeat=await Post("harbor/status",status);heartbeat.EnsureSuccessStatusCode();Assert(setup.Pcs.Snapshot().Single().Online&&setup.Pcs.Snapshot().Single().ModHash==info.ModHash,"Reported status missing");using var mod=await Post("harbor/mod",status);Assert(await mod.Content.ReadAsStringAsync()=="test-mod","Published wrong mod");using var unauthorized=await Post("harbor/mod",status with{Token=new string('A',64)});Assert((int)unauthorized.StatusCode==403,"Download accepted wrong token");using var changed=await Post("harbor/mod",status with{ModHash="bad"});Assert((int)changed.StatusCode==400,"Changed build accepted");checks.Add("Authenticated heartbeats drive actual online status; update download validates token and requested version");
        using var oversized=await http.PostAsync("harbor/status",new StringContent(new string('a',5000)));Assert((int)oversized.StatusCode==400,"Oversized request accepted");var registry=new LanPcRegistry(root);Assert(!registry.Snapshot().Single().Online,"Stale persisted status appears online");setup.Pcs.Forget(id);using var forgotten=await Post("harbor/status",status);Assert((int)forgotten.StatusCode==403,"Forgotten token still works");checks.Add("Oversized requests rejected; restarted host marks PCs offline until a fresh report; forgetting a PC revokes its token");ServerManager.WriteJson(report,new{passed=true,checks,realServerTouched=false});
    }
}
