using System.Drawing.Drawing2D;
namespace MinecraftHarbor;
public sealed partial class MainForm
{
    readonly PaintedPanel lanHow=new(),lanDownload=new(),lanConnected=new(),lanHelp=new(),lanAddress=new();
    readonly BackupViewport lanRows=new(){AccessibleName="Paired LAN PCs"};
    HarborButton lanWindows=null!,lanPair=null!;
    string lanSignature="";
    void BuildClientSetup()
    {
        var page=pages["LAN PCs"];page.AutoScroll=false;
        var title=LabelAt(page,"Set Up LAN PCs",0,0,900,58,31,Ink,true);var sub=LabelAt(page,"Keep your existing modpack ready to join your server.",0,0,900,33,13,ConsoleSyntax.Info);
        page.Controls.AddRange(new Control[]{lanHow,lanDownload,lanConnected,lanHelp,lanAddress});
        lanHow.Draw=DrawLanHow;lanDownload.Draw=DrawLanDownload;lanConnected.Draw=DrawLanConnected;lanHelp.Draw=(g,w,h)=>{BackupCard(g,w,h);HarborTheme.Text(g,"Troubleshooting",15,18,9,Ink,true);};lanAddress.Draw=DrawLanAddress;lanConnected.Controls.Add(lanRows);
        lanWindows=(HarborButton)MakeButton("Download AutoModpack",270,true);lanWindows.Glyph="download";lanWindows.Click+=async(_,_)=>await Run(()=>{setup.Helper();OpenPath(setup.Url+ClientSetup.HelperName);return Task.CompletedTask;});lanDownload.Controls.Add(lanWindows);
        var more=(HarborButton)MakeButton("…",36);more.Chrome=true;more.AccessibleName="Client setup tools";lanDownload.Controls.Add(more);more.Click+=(_,_)=>{var menu=new ContextMenuStrip();menu.Items.Add("Choose client pack folder",null,(_,_)=>ChooseClientSyncFolder());menu.Items.Add("Update custom Ultimine",null,async(_,_)=>await Run(()=>{if(!server.Profile.CustomUltimineSync||server.HasProcess||server.Busy||server.OtherServerRunning())throw new InvalidOperationException("Stop and save the ATM10 server before changing the custom mod.");using var file=new OpenFileDialog{Title="Choose custom FTB Ultimine",Filter="Minecraft mod (*.jar)|*.jar",CheckFileExists=true};if(file.ShowDialog(this)==DialogResult.OK){server.InstallUltimine(file.FileName);RefreshSetup();}return Task.CompletedTask;}));menu.Items.Add("View server fingerprint",null,(_,_)=>MessageBox.Show(this,setup.Fingerprint(),"Server fingerprint"));menu.Items.Add("Open setup page",null,(_,_)=>OpenPath(setup.Url));menu.Closed+=(_,_)=>BeginInvoke(()=>menu.Dispose());menu.Show(more,new Point(0,more.Height));};
        var copy=(HarborButton)MakeButton("",44);copy.Glyph="copy";copy.AccessibleName="Copy connection address";tips.SetToolTip(copy,"Copy connection address");copy.Click+=(_,_)=>Clipboard.SetText(setup.Url);lanAddress.Controls.Add(copy);
        lanPair=(HarborButton)MakeButton("Add PC Manually",220);lanPair.Glyph="plus";lanPair.Click+=(_,_)=>ShowPairing();lanConnected.Controls.Add(lanPair);
        string[] help={"PC cannot connect","Mods are not updating","View Logs"};for(int i=0;i<help.Length;i++){var b=(HarborButton)MakeButton(help[i],280);b.Chrome=true;b.Glyph=i==2?"folder":"help";int item=i;b.Click+=(_,_)=>{if(item==2)OpenPath(Path.Combine(server.Root,"logs"));else MessageBox.Show(this,item==0?"Keep Harbor open and both PCs on the same home network. Enter the setup address and a new pairing code in the client app. Guest Wi-Fi may isolate PCs. Existing LAN access uses port 25566.":"Check the pack version shown on the setup page, then use official AutoModpack to sync mods, configs and scripts when joining Minecraft.",help[item]);};lanHelp.Controls.Add(b);}
        void Arrange(){int u(int n)=>page.LogicalToDeviceUnits(n);int w=page.ClientSize.Width-u(3),gap=u(14),left=(w-gap)*68/100,right=w-gap-left,h=page.ClientSize.Height-u(123);
            title.SetBounds(0,u(12),w,u(58));sub.SetBounds(0,u(71),w,u(33));lanHow.SetBounds(0,u(123),left,u(192));lanDownload.SetBounds(0,u(329),left,Math.Max(u(147),page.ClientSize.Height-u(405)));lanWindows.SetBounds(u(18),u(72),left-u(36),u(44));more.SetBounds(left-u(54),u(12),u(36),u(34));lanAddress.SetBounds(0,page.ClientSize.Height-u(64),left,u(61));copy.SetBounds(left-u(58),u(11),u(44),u(39));
            lanConnected.SetBounds(left+gap,u(123),right,Math.Max(u(245),h-u(166)));lanRows.SetBounds(u(10),u(52),right-u(20),lanConnected.Height-u(109));lanPair.SetBounds(u(12),lanConnected.Height-u(48),right-u(24),u(38));lanHelp.SetBounds(left+gap,lanConnected.Bottom+u(14),right,u(148));int i=0;foreach(var button in lanHelp.Controls.OfType<HarborButton>())button.SetBounds(u(12),u(29+i++*36),right-u(24),u(34));RenderLanRows();
        }
        page.SizeChanged+=(_,_)=>Arrange();page.VisibleChanged+=(_,_)=>{if(page.Visible){Arrange();RefreshSetup();}};Arrange();
    }
    void DrawLanHow(Graphics g,float w,float h)
    {
        BackupCard(g,w,h);HarborTheme.Icon(g,"pc",18,17,28,ConsoleSyntax.Info);HarborTheme.Text(g,"How It Works",19,62,17,Ink,true);
        HarborTheme.Text(g,"Add official AutoModpack to your existing CurseForge pack, then join in Minecraft.",12,18,56,Muted,false,w-36);
        string[] titles={"1. Match Version","2. AutoModpack","3. Join Server","4. Sync"};string[] details={"Choose the required\nCurseForge release.","Replace the old\nAutoModpack JAR.","Launch and join\nthrough Minecraft.","Mods, configs\nand scripts update."};string[] icons={"download","folder","restart","play"};float cw=(w-45)/4;
        for(int i=0;i<4;i++){float x=12+i*(cw+7);using var path=HarborTheme.Round(new(x,84,cw,98),7);using var fill=new SolidBrush(Color.FromArgb(14,37,53));g.FillPath(fill,path);using var line=new Pen(Color.FromArgb(39,84,111));g.DrawPath(line,path);HarborTheme.Icon(g,icons[i],x+cw/2-13,90,26,ConsoleSyntax.Info);LanCenteredText(g,titles[i],12,new(x,123,cw,20),Ink,true);LanCenteredText(g,details[i],11,new(x+5,146,cw-10,36),Muted);}
    }
    static void LanCenteredText(Graphics g,string text,float size,RectangleF bounds,Color color,bool bold=false){using var font=new Font("Segoe UI",size,bold?FontStyle.Bold:FontStyle.Regular,GraphicsUnit.Pixel);using var brush=new SolidBrush(color);using var format=new StringFormat{Alignment=StringAlignment.Center,LineAlignment=StringAlignment.Center};g.DrawString(text,font,brush,bounds,format);}
    void DrawLanDownload(Graphics g,float w,float h){BackupCard(g,w,h);HarborTheme.Text(g,"Download AutoModpack",19,18,15,Ink,true);HarborTheme.Text(g,"Minecraft 1.21.1 · NeoForge · Your existing CurseForge profile",12,18,45,Muted,false,w-36);HarborTheme.Text(g,$"Required: {server.Profile.Name} {server.Profile.PackVersion}",11,18,126,Muted,false,w-36);}
    void DrawLanConnected(Graphics g,float w,float h){BackupCard(g,w,h);HarborTheme.Icon(g,"pc",15,15,25,Muted);HarborTheme.Text(g,"Connected PCs",16,50,17,Ink,true,w-130);var pcs=setup.Pcs.Snapshot();HarborTheme.Text(g,$"{pcs.Count(p=>p.Online)} / {pcs.Count} online",11,w-98,21,ConsoleSyntax.Success,false,86,true);}
    void DrawLanAddress(Graphics g,float w,float h){BackupCard(g,w,h);HarborTheme.Icon(g,"link",15,18,25,Muted);HarborTheme.Text(g,"Connection Address",12,53,9,Ink,true,w-165);HarborTheme.Text(g,setup.Url,12,53,31,Muted,false,w-165);}
    void RefreshSetup(){if(lanWindows==null)return;lanWindows.Enabled=File.Exists(Path.Combine(server.Root,"client-setup",ClientSetup.HelperName));RenderLanRows();lanConnected.Invalidate();lanDownload.Invalidate();lanAddress.Invalidate();}
    void RenderLanRows()
    {
        if(lanPair==null)return;var pcs=setup.Pcs.Snapshot();string expected=setup.Publisher?.CachedHash??"";string signature=string.Join('|',pcs.Select(p=>p.Id+p.Name+p.Address+p.Online+p.GameRunning+p.Message+p.ModHash))+lanRows.Width+server.Profile.Id+expected;if(signature==lanSignature)return;lanSignature=signature;lanRows.AutoScrollPosition=Point.Empty;foreach(Control c in lanRows.Controls.Cast<Control>().Where(c=>c is not BackupScrollRail).ToArray())c.Dispose();int u(int n)=>lanRows.LogicalToDeviceUnits(n);
        if(pcs.Count==0){LabelAt(lanRows,"No PCs paired yet.\nUse Add PC Manually to connect the client.",u(9),u(17),lanRows.Width-u(29),u(75),11,Muted);lanRows.AutoScrollMinSize=Size.Empty;return;}
        int index=0;foreach(var pc in pcs){var row=new PaintedPanel{BackColor=BackupViewport.Surface};string status=!pc.Online?"Offline":pc.GameRunning?"Playing":pc.ModHash.Length>0&&pc.ModHash==expected?"Up to date":pc.Message.Length>0?pc.Message:"Connected";row.Draw=(g,w,h)=>{HarborTheme.Icon(g,"pc",7,13,22,Muted);HarborTheme.Text(g,pc.Name,12,39,8,Ink,true,w-70);HarborTheme.Text(g,pc.Address,10,39,30,Muted,false,w-70);HarborTheme.Text(g,status,10,39,48,pc.Online?ConsoleSyntax.Success:Muted,false,w-50);using var line=new Pen(Color.FromArgb(34,65,86));g.DrawLine(line,8,h-1,w-9,h-1);};row.SetBounds(0,u(index++*76),lanRows.Width-u(17),u(76));lanRows.Controls.Add(row);var menu=(HarborButton)MakeButton("…",27);menu.Chrome=true;menu.SetBounds(row.Width-u(31),u(9),u(27),u(28));menu.Click+=(_,_)=>{var options=new ContextMenuStrip();options.Items.Add("Forget PC",null,async(_,_)=>{if(MessageBox.Show(this,"Disconnect "+pc.Name+" from Harbor? It will need a new pairing code.","Forget PC",MessageBoxButtons.YesNo)==DialogResult.Yes)await Run(()=>{setup.Pcs.Forget(pc.Id);RenderLanRows();return Task.CompletedTask;});});options.Closed+=(_,_)=>BeginInvoke(()=>options.Dispose());options.Show(menu,new Point(0,menu.Height));};row.Controls.Add(menu);}
        lanRows.AutoScrollMinSize=new(0,u(index*76));
    }
    void ShowPairing(){string code=setup.Pcs.NewCode();using var dialog=new Form{Text="Pair a LAN PC",ClientSize=new(520,252),StartPosition=FormStartPosition.CenterParent,FormBorderStyle=FormBorderStyle.FixedDialog,MinimizeBox=false,MaximizeBox=false,BackColor=Bg,ForeColor=Ink,Font=Font};LabelAt(dialog,"Connect your Harbor Client",22,18,476,36,20,Ink,true);LabelAt(dialog,"Enter this address and code in the client app.",24,64,470,28,11,Muted);LabelAt(dialog,setup.Url,24,99,470,32,16,Ink);LabelAt(dialog,code,24,137,470,45,27,Mint,true);LabelAt(dialog,"One PC · expires in 10 minutes",24,188,340,25,10,Muted);var done=MakeButton("Done",100);done.SetBounds(392,196,100,38);done.Click+=(_,_)=>dialog.Close();dialog.Controls.Add(done);ScaleDialog(dialog);dialog.ShowDialog(this);}
    void ChooseClientSyncFolder(){using var dialog=new FolderBrowserDialog{Description="Choose the client modpack folder to share with your LAN PCs",UseDescriptionForTitle=true,ShowNewFolderButton=false};if(dialog.ShowDialog(this)!=DialogResult.OK)return;try{var profile=CurseForgeProfiles.Read(dialog.SelectedPath);if(profile.MinecraftVersion!=server.Profile.MinecraftVersion||profile.Loader!=server.Profile.Loader||server.Profile.ProjectId>0&&profile.ProjectId!=server.Profile.ProjectId)throw new InvalidDataException("Choose the matching modpack, Minecraft version, and loader.");server.Profile.ClientSyncPath=dialog.SelectedPath;server.Library.Save();RefreshSetup();}catch(Exception ex){MessageBox.Show(this,ex.Message,"Client pack folder");}}
}
