using System.IO.Compression;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
namespace MinecraftHarbor;
internal static class ModrinthTests
{
    internal static async Task Run(string report)
    {
        string root=Path.Combine(Path.GetDirectoryName(Path.GetFullPath(report))!,"modrinth-fixture-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);var checks=new List<string>();void Check(bool b,string error){if(!b)throw new Exception(error);}
        var handler=new FixtureHttp();using var http=new HttpClient(handler);var catalog=new CurseForgeCatalog(root,http);var page=await catalog.CombinedSearch("tech & magic",2,1,false,CancellationToken.None);
        Check(page.Items.Single().Source=="Modrinth"&&!catalog.Connected&&handler.LastQuery.Contains("offset=20")&&handler.LastQuery.Contains("tech%20%26%20magic"),"No-key search or pagination failed");checks.Add("Combined browser works with no key, identifies Modrinth as the source and sends its required User-Agent without CurseForge credentials");
        var releases=await catalog.Modrinth.Files("pack0001",CancellationToken.None);var draft=await catalog.Inspect(page.Items[0],releases.Single(),CancellationToken.None,_=>{});
        using(var zip=ZipFile.OpenRead(draft.Archive)){Check(zip.GetEntry("mods/base.jar")!=null&&zip.GetEntry("mods/client.jar")==null&&zip.GetEntry("config/client-only.txt")==null,"Client-only content entered the server");using var read=new StreamReader(zip.GetEntry("config/example.toml")!.Open());Check(read.ReadToEnd().Contains("rate = 8"),"Server overrides did not override common files");}
        Check(draft.ModFiles.ContainsKey(ModrinthCatalog.Id("base0001"))&&draft.Source.MinecraftVersion=="1.21.1"&&draft.Source.LoaderVersion=="21.1.249"&&draft.Config.Count==2,"Pack metadata or included mods were not identified");checks.Add("MRPACK imports use the exact game and loader, omit client-only files, apply server overrides after common overrides and discover editable configuration");
        var baseId=ModrinthCatalog.Id("base0001");draft.ModFiles[555]=draft.ModFiles[baseId] with{ModId=555};draft.Mods[555]=new(555,"CurseForge base","","","",0,new());draft.ModFiles.Remove(baseId);draft.Mods.Remove(baseId);await catalog.Modrinth.IdentifyIncluded(draft,CancellationToken.None);Check(draft.Aliases[555]==baseId&&(await catalog.ResolveAddition(draft,new(555,"CurseForge base","","","",0,new()),CancellationToken.None)).Count==0,"Cross-library identity duplicated an installed mod");checks.Add("Published file hashes identify the same installed mod across both libraries and prevent duplicate installation");
        int count=handler.Downloads;await catalog.Inspect(page.Items[0],releases.Single(),CancellationToken.None,_=>{});Check(handler.Downloads==count,"Cached release was downloaded again");File.WriteAllText(draft.Archive,"corrupt assembled cache");await catalog.Inspect(page.Items[0],releases.Single(),CancellationToken.None,_=>{});Check(handler.Downloads==count,"Repair downloaded checked files again");checks.Add("The same pack release reuses checked downloads and its assembled server ZIP; a damaged assembled ZIP is rebuilt without repeating transfers");
        var additions=await catalog.ResolveAddition(draft,await catalog.Modrinth.Project("added001",CancellationToken.None),CancellationToken.None);Check(additions.Count==2&&additions.ContainsKey(ModrinthCatalog.Id("dep00001")),"Required dependencies were not resolved");checks.Add("Added mods resolve pinned required dependencies, handle cycles and filter exact Minecraft/loader versions");
        handler.WrongLoader=true;bool rejected=false;try{await catalog.ResolveAddition(draft,await catalog.Modrinth.Project("added001",CancellationToken.None),CancellationToken.None);}catch(InvalidDataException){rejected=true;}Check(rejected,"Wrong-loader pinned dependency was accepted");handler.WrongLoader=false;
        handler.Incompatible=true;rejected=false;try{await catalog.ResolveAddition(draft,await catalog.Modrinth.Project("added001",CancellationToken.None),CancellationToken.None);}catch(InvalidOperationException){rejected=true;}Check(rejected,"Incompatibility was ignored");handler.Incompatible=false;checks.Add("Wrong-loader pinned dependencies and declared incompatible mods are rejected");
        var added=additions[ModrinthCatalog.Id("added001")];string cached=await catalog.Download(added,CancellationToken.None);File.WriteAllText(cached,"corrupt");int prior=handler.Downloads;await catalog.Download(added,CancellationToken.None);Check(handler.Downloads==prior+1,"Damaged cache was accepted");handler.Damaged=true;rejected=false;try{await catalog.Download(additions[ModrinthCatalog.Id("dep00001")],CancellationToken.None);}catch(InvalidDataException){rejected=true;}Check(rejected&&!Directory.EnumerateFiles(root,"*.partial",SearchOption.AllDirectories).Any(),"Damaged download remained");handler.Damaged=false;checks.Add("SHA1 and SHA512 protect transfers and cached files; corrupt cache is replaced and incomplete downloads are discarded");
        Directory.CreateDirectory(Path.Combine(root,"runtime","bin"));File.WriteAllText(Path.Combine(root,"runtime","bin","java.exe"),"fixture, never executed");LibraryTests.WriteWorld(Path.Combine(root,"server","world"));var original=File.ReadAllBytes(Path.Combine(root,"server","world","level.dat"));using var manager=new ServerManager(root);
        draft.Added=additions;await manager.CreateModdedAsync(draft,new Settings{MemoryGB=8,WorldName="Modrinth world"},"Modrinth server",new(),new(){{"keepInventory","true"}},false,catalog,CancellationToken.None);var first=manager.Library.Data.Profiles.Last();string firstRoot=manager.Library.ProfileRoot(first);Check(File.Exists(Path.Combine(firstRoot,"server","mods","added.jar"))&&File.Exists(Path.Combine(firstRoot,"server","mods","dependency.jar")),"Server additions did not install");
        draft.Added.Clear();await manager.CreateModdedAsync(draft,new Settings{MemoryGB=16,WorldName="Second world"},"Second Modrinth server",new(),new(),false,catalog,CancellationToken.None);var second=manager.Library.Data.Profiles.Last();Check(!File.Exists(Path.Combine(manager.Library.ProfileRoot(second),"server","mods","added.jar"))&&Directory.GetDirectories(Path.Combine(root,"pack-cache")).Length==1&&File.ReadAllBytes(Path.Combine(root,"server","world","level.dat")).SequenceEqual(original),"Template or active world changed");checks.Add("Two Modrinth servers share prepared base files while added mods, world names, rules and RAM remain independent; the active world is unchanged");
        handler.Unsafe=true;var bad=handler.PackRelease();rejected=false;try{await catalog.Inspect(page.Items[0],bad,CancellationToken.None,_=>{});}catch(InvalidDataException){rejected=true;}Check(rejected&&!File.Exists(Path.Combine(root,"escape.jar")),"Unsafe manifest path was accepted");checks.Add("Unsafe manifest paths are rejected before extraction or download");
        ServerManager.WriteJson(report,new{passed=true,checks,fixtureRoot=root,realWorldModified=false});
    }
    internal static async Task Live(string report)
    {
        string root=Path.Combine(Path.GetDirectoryName(Path.GetFullPath(report))!,"modrinth-live");var catalog=new CurseForgeCatalog(root);using var timeout=new CancellationTokenSource(TimeSpan.FromMinutes(5));var page=await catalog.CombinedSearch("server",6,0,false,timeout.Token);if(page.Items.Count==0)throw new Exception("No live Modrinth packs returned");var project=await catalog.Modrinth.Project("ferrite-core",timeout.Token);var versions=await catalog.Modrinth.Files(project.ModrinthId,timeout.Token,"1.21.1","neoforge");var file=versions.First();string path=await catalog.Download(file,timeout.Token);await catalog.Download(file,timeout.Token);var hash=await catalog.Modrinth.MatchHash(file.Sha1,timeout.Token);if(hash==null||hash.ModId!=file.ModId)throw new Exception("Published hash lookup did not match");
        ServerManager.WriteJson(report,new{passed=true,catalogCount=page.Items.Count,catalogTotal=page.Total,download=path,file.DisplayName,file.Length,checks=new[]{"Live no-key Modrinth modpack search","Live game/loader filtered mod release","Real mod download with SHA1/SHA512 verification and cache reuse","Exact-file hash lookup for cross-library preference"},realWorldModified=false});
    }
    internal sealed class FixtureHttp:HttpMessageHandler
    {
        internal int Downloads;internal string LastQuery="";internal bool WrongLoader,Incompatible,Damaged,Unsafe;
        byte[] Jar(string id){using var memory=new MemoryStream();using(var zip=new ZipArchive(memory,ZipArchiveMode.Create,true)){using var writer=new StreamWriter(zip.CreateEntry("META-INF/neoforge.mods.toml").Open());writer.Write("[[mods]]\nmodId=\""+id+"\"\nversion=\"1\"\n");}return memory.ToArray();}
        readonly Dictionary<string,byte[]> jars=new();
        byte[]? validPack,unsafePack;
        internal FixtureHttp(){jars["base.jar"]=Jar("base");jars["added.jar"]=Jar("added");jars["dependency.jar"]=Jar("dependency");}
        object Project(string id)=>new{id,project_id=id,project_type=id=="pack0001"?"modpack":"mod",title=id=="pack0001"?"Fixture Modrinth Pack":id,description="Fixture",icon_url="",slug=id,downloads=100,server_side="required"};
        byte[] Pack(){if(Unsafe&&unsafePack!=null)return unsafePack;if(!Unsafe&&validPack!=null)return validPack;using var m=new MemoryStream();using(var zip=new ZipArchive(m,ZipArchiveMode.Create,true)){
            var bytes=jars["base.jar"];object Entry(string path,string server)=>new{path,hashes=new{sha1=Convert.ToHexString(SHA1.HashData(bytes)).ToLowerInvariant(),sha512=Convert.ToHexString(SHA512.HashData(bytes)).ToLowerInvariant()},env=new{client="required",server},downloads=new[]{"https://cdn.modrinth.com/base.jar"},fileSize=bytes.Length};
            using(var writer=new StreamWriter(zip.CreateEntry("modrinth.index.json").Open()))writer.Write(JsonSerializer.Serialize(new{formatVersion=1,game="minecraft",versionId="1",name="Fixture",dependencies=new Dictionary<string,string>{{"minecraft","1.21.1"},{"neoforge","21.1.249"}},files=new[]{Entry(Unsafe?"../escape.jar":"mods/base.jar","required"),Entry("mods/client.jar","unsupported")}}));
            foreach(var p in new[]{("overrides/config/example.toml","[general]\nrate = 3\nenabled = true\n"),("server-overrides/config/example.toml","[general]\nrate = 8\nenabled = true\n"),("client-overrides/config/client-only.txt","skip"),("server-overrides/libraries/net/neoforged/neoforge/21.1.249/win_args.txt","fixture, never executed")}){using var writer=new StreamWriter(zip.CreateEntry(p.Item1).Open());writer.Write(p.Item2);}
        }var encodedPack=m.ToArray();if(Unsafe)unsafePack=encodedPack;else validPack=encodedPack;return encodedPack;}
        internal CfFile PackRelease()=>ModrinthCatalog.VersionInfo(JsonSerializer.SerializeToElement(Version("pack0001","packver1")));
        object Version(string project,string version)
        {
            string name=project=="pack0001"?"pack.mrpack":project=="base0001"?"base.jar":project=="added001"?"added.jar":"dependency.jar";byte[] bytes=project=="pack0001"?Pack():jars[name];var dependencies=new List<object>();if(project=="added001")dependencies.Add(new{project_id="dep00001",version_id="depver01",dependency_type="required"});if(project=="dep00001")dependencies.Add(new{project_id="added001",version_id="addedver",dependency_type="required"});if(Incompatible&&project=="added001")dependencies.Add(new{project_id="base0001",version_id=(string?)null,dependency_type="incompatible"});
            return new{id=version,project_id=project,name=project,version_number="1",game_versions=new[]{"1.21.1"},loaders=new[]{WrongLoader&&project=="dep00001"?"forge":"neoforge"},dependencies,files=new[]{new{primary=true,filename=name,size=bytes.Length,url="https://cdn.modrinth.com/"+name,hashes=new{sha1=Convert.ToHexString(SHA1.HashData(bytes)).ToLowerInvariant(),sha512=Convert.ToHexString(SHA512.HashData(bytes)).ToLowerInvariant()}}}};
        }
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken token)
        {
            if(request.Headers.Contains("x-api-key")||!request.Headers.UserAgent.Any())throw new Exception("Wrong Modrinth headers");token.ThrowIfCancellationRequested();var uri=request.RequestUri!;if(uri.Host=="cdn.modrinth.com"){Downloads++;byte[] bytes=uri.AbsolutePath.EndsWith(".mrpack")?Pack():jars[Path.GetFileName(uri.AbsolutePath)];return new(HttpStatusCode.OK){Content=new ByteArrayContent(Damaged?Encoding.UTF8.GetBytes("bad"):bytes)};}
            LastQuery=uri.Query;string path=uri.AbsolutePath;object data;
            if(path.EndsWith("search"))data=new{hits=new[]{Project("pack0001")},total_hits=40};
            else if(path.EndsWith("version_files")){using var json=JsonDocument.Parse(await request.Content!.ReadAsStringAsync(token));var hashes=json.RootElement.GetProperty("hashes").EnumerateArray().Select(v=>v.GetString()).ToHashSet();var result=new Dictionary<string,object>();string hash=Convert.ToHexString(SHA1.HashData(jars["base.jar"])).ToLowerInvariant();if(hashes.Contains(hash))result[hash]=Version("base0001","basever1");data=result;}
            else if(path.EndsWith("projects"))data=new[]{Project("base0001")};
            else if(path.Contains("/project/")&&path.EndsWith("/version")){string id=path.Split('/')[3];data=new[]{Version(id,id=="pack0001"?"packver1":"addedver")};}
            else if(path.Contains("/project/"))data=Project(path.Split('/').Last());
            else if(path.Contains("/version/")){string id=path.Split('/').Last();data=Version(id=="depver01"?"dep00001":"added001",id);}
            else throw new Exception("Unexpected Modrinth test URL "+uri);
            return new(HttpStatusCode.OK){Content=new StringContent(JsonSerializer.Serialize(data))};
        }
    }
    internal static async Task LivePack(string report,string runtime)
    {
        string root=Path.Combine(Path.GetDirectoryName(Path.GetFullPath(report))!,"modrinth-server-smoke-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);var catalog=new CurseForgeCatalog(root);using var deadline=new CancellationTokenSource(TimeSpan.FromMinutes(8));void Activity(string value)=>File.AppendAllText(Path.Combine(root,"setup.log"),value+Environment.NewLine);
        var project=await catalog.Modrinth.Project("server-plus",deadline.Token);var releases=await catalog.Modrinth.Files(project.ModrinthId,deadline.Token,"1.21.1","fabric");var draft=await catalog.Inspect(project,releases.First(),deadline.Token,Activity);await Task.Run(()=>PackInstaller.CopyTree(runtime,Path.Combine(root,"runtime"),deadline.Token),deadline.Token);
        var profile=await PackInstaller.PrepareAsync(root,draft.Source,Activity,deadline.Token,draft.Archive);string folder=Path.Combine(root,"profiles",profile.Id,"server");File.WriteAllText(Path.Combine(folder,"eula.txt"),"eula=true\n");
        var listener=new System.Net.Sockets.TcpListener(IPAddress.Loopback,0);listener.Start();int port=((IPEndPoint)listener.LocalEndpoint).Port;listener.Stop();File.WriteAllText(Path.Combine(folder,"server.properties"),$"server-ip=127.0.0.1\nserver-port={port}\nlevel-name=world\nview-distance=5\nsimulation-distance=4\nonline-mode=true\n");
        var start=new System.Diagnostics.ProcessStartInfo(profile.JavaPath){WorkingDirectory=folder,CreateNoWindow=true,UseShellExecute=false,RedirectStandardInput=true,RedirectStandardOutput=true,RedirectStandardError=true};foreach(var arg in new[]{"-Xms1G","-Xmx2G","-jar",profile.LaunchFile,"nogui"})start.ArgumentList.Add(arg);
        using var process=new System.Diagnostics.Process{StartInfo=start};var ready=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var log=new List<string>();object logLock=new();async Task Read(StreamReader reader){string? line;while((line=await reader.ReadLineAsync())!=null){lock(logLock)log.Add(line);if(line.Contains("Done (")&&line.Contains("For help"))ready.TrySetResult();}}
        process.Start();var output=Read(process.StandardOutput);var error=Read(process.StandardError);bool started=false,stopped=false;
        try{var exit=process.WaitForExitAsync();var completed=await Task.WhenAny(ready.Task,exit,Task.Delay(TimeSpan.FromMinutes(5),deadline.Token));if(completed!=ready.Task)throw new Exception("The disposable Modrinth server did not finish starting. See the smoke log.");started=true;await process.StandardInput.WriteLineAsync("gamerule keepInventory true");await Task.Delay(1000,deadline.Token);}
        finally{if(!process.HasExited){await process.StandardInput.WriteLineAsync("stop");if(await Task.WhenAny(process.WaitForExitAsync(),Task.Delay(TimeSpan.FromSeconds(45)))!=process.WaitForExitAsync()) {if(!process.HasExited){process.Kill(true);await process.WaitForExitAsync();}}}await Task.WhenAll(output,error);stopped=process.ExitCode==0;File.WriteAllLines(Path.Combine(root,"server.log"),log);}
        if(!started||!stopped||!File.Exists(Path.Combine(folder,"world","level.dat")))throw new Exception("The disposable server did not save and stop cleanly.");
        int downloads=Directory.EnumerateFiles(Path.Combine(root,"downloads","modrinth"),"*.jar",SearchOption.AllDirectories).Count();int mods=Directory.EnumerateFiles(Path.Combine(folder,"mods"),"*.jar").Count();ServerManager.WriteJson(report,new{passed=true,fixtureRoot=root,project.Name,profile.MinecraftVersion,profile.Loader,mods,downloads,worldGenerated=true,savedAndStopped=true,port,realWorldModified=false,checks=new[]{"Real Modrinth pack assembly and published file hashes","Real Fabric loader preparation","Actual dedicated server reached Done on a separate loopback port","Game rule accepted, world generated, saved and stopped cleanly"}});
    }
}
