using System.IO.Compression;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
namespace MinecraftHarbor;
internal static class PackPublishTests
{
    internal static async Task Run(string report)
    {
        string root=Path.Combine(Path.GetDirectoryName(Path.GetFullPath(report))!,"pack-publish-"+Guid.NewGuid().ToString("N"));PlayerTests.Fixture(root,1);using var server=new ServerManager(root);string client=Path.Combine(root,"client");Directory.CreateDirectory(Path.Combine(client,"mods"));Directory.CreateDirectory(Path.Combine(client,"config"));Directory.CreateDirectory(Path.Combine(client,"saves"));
        void Jar(string path,string id,string content){Directory.CreateDirectory(Path.GetDirectoryName(path)!);using var zip=ZipFile.Open(path,ZipArchiveMode.Create);using var writer=new StreamWriter(zip.CreateEntry("META-INF/neoforge.mods.toml").Open());writer.Write("[[mods]]\nmodId=\""+id+"\"\n# "+content);}
        Jar(Path.Combine(client,"mods/old-name.jar"),"machine","client");Jar(Path.Combine(client,"mods/client-only.jar"),"map","client-only");Jar(Path.Combine(server.ServerDir,"mods/new-name.jar"),"machine","server");File.WriteAllText(Path.Combine(client,"config/test.toml"),"rate=1");File.WriteAllText(Path.Combine(client,"saves/world.txt"),"private");Directory.CreateDirectory(Path.Combine(server.ServerDir,"config"));File.WriteAllText(Path.Combine(server.ServerDir,"config/test.toml"),"rate=8");server.Profile.ClientSyncPath=client;server.Profile.ProjectId=22;
        using var setup=new ClientSetup(root,()=>server,0);var first=setup.Publisher!.Manifest();void Assert(bool v,string text){if(!v)throw new Exception(text);}Assert(first.Files.Any(f=>f.Path=="mods/new-name.jar")&&first.Files.Any(f=>f.Path=="mods/client-only.jar")&&!first.Files.Any(f=>f.Path=="mods/old-name.jar"||f.Path.StartsWith("saves/")),"Server overrides or client-only handling failed");Assert(first.Files.All(f=>f.Path.StartsWith("mods/")&&f.Path.EndsWith(".jar")),"Non-mod content published");
        File.Delete(Path.Combine(server.ServerDir,"mods/new-name.jar"));var second=setup.Publisher.Manifest();Assert(!second.Files.Any(f=>f.Path=="mods/old-name.jar"),"Server removal resurrected old client mod");File.WriteAllText(Path.Combine(client,"config/changed.toml"),"new setting");var third=setup.Publisher.Manifest();Assert(!third.Files.Any(f=>f.Path=="mods/old-name.jar")&&third.Hash==second.Hash,"Persisted server removal lost");
        bool rejected=false;try{setup.Publisher.FileFor(first.Hash,"mods/../../settings.json");}catch(InvalidOperationException){rejected=true;}Assert(rejected,"Old snapshot accepted");
        setup.Start();using var http=new HttpClient{BaseAddress=new("http://127.0.0.1:"+setup.ListeningPort+"/")};async Task<HttpResponseMessage> Post<T>(string route,T value){using var body=new StringContent(JsonSerializer.Serialize(value),Encoding.UTF8,"application/json");return await http.PostAsync(route,body);}string id=Guid.NewGuid().ToString();using var pair=await Post("harbor/pair",new LanPairRequest(setup.Pcs.NewCode(),id,"PC"));pair.EnsureSuccessStatusCode();string token=(await pair.Content.ReadFromJsonAsync<LanPairResponse>())!.Token;using var manifest=await Post("harbor/manifest",new PackSyncRequest(id,token,""));manifest.EnsureSuccessStatusCode();Assert((await manifest.Content.ReadFromJsonAsync<PackSyncManifest>())!.Hash==third.Hash,"HTTP manifest mismatch");using var download=await Post("harbor/file",new PackSyncRequest(id,token,third.Hash,"mods/client-only.jar"));download.EnsureSuccessStatusCode();Assert((await download.Content.ReadAsByteArrayAsync()).SequenceEqual(File.ReadAllBytes(Path.Combine(client,"mods/client-only.jar"))),"HTTP file mismatch");using var bad=await Post("harbor/file",new PackSyncRequest(id,new string('A',64),third.Hash,"config/test.toml"));Assert((int)bad.StatusCode==403,"Unauthenticated content download");using var traversal=await Post("harbor/file",new PackSyncRequest(id,token,third.Hash,"mods/../../settings.json"));Assert((int)traversal.StatusCode==400,"Traversal accepted");
        ServerManager.WriteJson(report,new{passed=true,checks=new[]{"Client-only mods retained; server mod version replaces old filename by identity; configs and Minecraft files excluded","Removed server mods stay removed across future snapshots; unrelated config changes do not change the manifest","Actual authenticated HTTP manifest and file downloads; wrong token, stale snapshot, and traversal rejected"},realServerTouched=false});
    }
}
