using System.Diagnostics;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace MinecraftHarbor;
internal static class PlayerTests
{
    internal static string Id(int number)=>new Guid(number,0,0,new byte[8]).ToString();
    internal static void Fixture(string root,int count=17)
    {
        LibraryTests.WriteWorld(Path.Combine(root,"server","world"));Directory.CreateDirectory(Path.Combine(root,"server","world","stats"));File.WriteAllText(Path.Combine(root,"server","eula.txt"),"eula=true");ServerManager.WriteJson(Path.Combine(root,"settings.json"),new Settings{MemoryGB=8,OwnerName="OwnerPlayer",OwnerUuid=Id(1),WorldName="Players test world"});
        var cache=Enumerable.Range(1,count).Select(i=>new Player(Id(i),i==1?"OwnerPlayer":i==2?"TestOwner":i==3?"FriendPlayer":"Player"+i.ToString("00"))).ToArray();
        ServerManager.WriteJson(Path.Combine(root,"server","usercache.json"),cache);ServerManager.WriteJson(Path.Combine(root,"server","whitelist.json"),cache.Take(3));ServerManager.WriteJson(Path.Combine(root,"server","ops.json"),new[]{new{uuid=Id(1),name="OwnerPlayer",level=4,bypassesPlayerLimit=true},new{uuid=Id(2),name="TestOwner",level=2,bypassesPlayerLimit=false}});ServerManager.WriteJson(Path.Combine(root,"server","banned-players.json"),new[]{new{uuid=Id(5),name="Player05",created="2026-10-01 12:00:00 +00:00",source="Test",expires="forever",reason="Fixture ban"}});
        foreach(var player in cache){ServerManager.WriteJson(Path.Combine(root,"server","world","stats",player.uuid+".json"),new{stats=new Dictionary<string,object>{{"minecraft:custom",new Dictionary<string,long>{{"minecraft:play_time",146000}}}}});}
    }
    internal static bool MockCommand(string line)
    {
        var args=line.Split(' ',StringSplitOptions.RemoveEmptyEntries);if(args.Length<2)return false;string verb=args[0];if(verb is not ("whitelist" or "op" or "deop" or "ban" or "pardon" or "kick" or "tp"))return false;
        string name=verb=="whitelist"&&args.Length>2?args[2]:args[1];if(verb=="whitelist"&&(args.Length<3||args[1] is not ("add" or "remove")))return false;
        if(verb=="kick"||verb=="tp"){Console.WriteLine("[12:00:00] [Server thread/INFO]: "+(verb=="kick"?"Kicked "+name+": Test":"Teleported "+name+" to "+args.Last()));return true;}
        string file=verb=="whitelist"?"whitelist.json":verb is "op" or "deop"?"ops.json":"banned-players.json";var path=Path.Combine(Environment.CurrentDirectory,file);var list=File.Exists(path)?JsonNode.Parse(File.ReadAllText(path)) as JsonArray??new():new JsonArray();var cached=PlayerDirectory.ReadArray(Path.Combine(Environment.CurrentDirectory,"usercache.json")).FirstOrDefault(p=>PlayerDirectory.Text(p,"name")==name);string id=cached.ValueKind==JsonValueKind.Undefined?Guid.NewGuid().ToString():PlayerDirectory.Text(cached,"uuid");foreach(var item in list.Where(n=>n?["name"]?.GetValue<string>()==name).ToArray())list.Remove(item);
        bool add=verb is "op" or "ban"||verb=="whitelist"&&args[1]=="add";if(add){var item=new JsonObject{["uuid"]=id,["name"]=name};if(verb=="op"){item["level"]=4;item["bypassesPlayerLimit"]=false;}if(verb=="ban"){item["expires"]="forever";item["reason"]="Fixture action";}list.Add(item);}ServerManager.WriteJson(path,list);
        string message=verb switch{"whitelist"=>add?"Added "+name+" to the whitelist":"Removed "+name+" from the whitelist","op"=>"Made "+name+" a server operator","deop"=>"Made "+name+" no longer a server operator","ban"=>"Banned "+name+": Test",_=>"Unbanned "+name};Console.WriteLine("[12:00:00] [Server thread/INFO]: "+message);return true;
    }
    internal static async Task Run(string report)
    {
        report=Path.GetFullPath(report);var root=Path.Combine(Path.GetDirectoryName(report)!,"players-fixture-"+Guid.NewGuid().ToString("N"));Fixture(root);ProcessStartInfo Launcher(){var info=new ProcessStartInfo(Environment.ProcessPath!);info.ArgumentList.Add("--mock-server");return info;}using var manager=new ServerManager(root,Launcher);var checks=new List<string>();void Assert(bool pass,string message){if(!pass)throw new Exception(message);}
        try{
            var players=manager.ManagedPlayers();Assert(players.Count==17&&players.Count(p=>p.Whitelisted)==3&&players.Count(p=>p.OperatorLevel>0)==2&&players.Count(p=>p.Banned)==1,"Lists were not merged correctly");Assert(players.All(p=>p.PlayTicks==146000)&&players.All(p=>p.LastSeenUtc==null),"Saved stats or unknown last-seen data fabricated");Assert(players.First().Playtime=="2h 1m","Playtime conversion failed");checks.Add("Deduplicated real list sources, roles, whitelist and bans; playtime from saved statistics; unknown last-seen remains unknown");
            manager.ObservePlayerPresence("[12:00:00] [Server thread/INFO]: TestOwner joined the game");manager.ObservePlayerPresence("[12:00:00] [Server thread/INFO]: TestOwner joined the game");Assert(manager.OnlinePlayers==1&&manager.OnlineNames=="TestOwner","Repeated join inflated online count");manager.ObservePlayerPresence("[12:00:00] [Server thread/INFO]: <FriendPlayer> TestOwner left the game");Assert(manager.OnlinePlayers==1,"Player chat spoofed leave");manager.ObservePlayerPresence("[12:00:00] [Server thread/INFO]: There are 2 of a max of 8 players online: TestOwner, FriendPlayer");Assert(manager.OnlinePlayers==2&&manager.ManagedPlayers().Count(p=>p.Online)==2,"List did not reconcile names");manager.ObservePlayerPresence("[12:00:00] [Server thread/INFO]: TestOwner left the game");Assert(manager.ManagedPlayers().Single(p=>p.Name=="TestOwner").LastSeenUtc.HasValue,"Last seen not persisted");checks.Add("Join/leave and list reconcile live names without duplicates or spoofed player chat; last-seen persists per world");
            var target=new Player(Id(4),"Player04");await manager.PlayerActionAsync(PlayerAction.Whitelist,target);Assert(manager.ManagedPlayers().Single(p=>p.Uuid==target.uuid).Whitelisted,"Offline whitelist add failed");await manager.PlayerActionAsync(PlayerAction.RemoveWhitelist,target);await manager.PlayerActionAsync(PlayerAction.Operator,target);Assert(manager.ManagedPlayers().Single(p=>p.Uuid==target.uuid).OperatorLevel==4,"Offline operator add failed");await manager.PlayerActionAsync(PlayerAction.RemoveOperator,target);await manager.PlayerActionAsync(PlayerAction.Ban,target,"Test reason");Assert(manager.ManagedPlayers().Single(p=>p.Uuid==target.uuid).BanReason=="Test reason","Ban did not persist reason");await manager.PlayerActionAsync(PlayerAction.Unban,target);Assert(!manager.ManagedPlayers().Single(p=>p.Uuid==target.uuid).Banned,"Unban failed");Assert(PlayerDirectory.ReadArray(Path.Combine(manager.ServerDir,"ops.json")).Single(e=>PlayerDirectory.Text(e,"uuid")==Id(1)).GetProperty("bypassesPlayerLimit").GetBoolean(),"Untouched operator fields lost");
            foreach(var action in new[]{PlayerAction.RemoveWhitelist,PlayerAction.RemoveOperator,PlayerAction.Ban}){bool rejected=false;try{await manager.PlayerActionAsync(action,new(Id(1),"OwnerPlayer"));}catch(InvalidOperationException){rejected=true;}Assert(rejected,"Owner access could be removed");}bool injected=false;try{ServerManager.PlayerCommand(PlayerAction.Kick,new(Id(2),"TestOwner\nstop"));}catch(ArgumentException){injected=true;}Assert(injected,"Player command injection accepted");checks.Add("Offline whitelist, operator and ban actions preserve unrelated fields; owner access and command validation are protected");
            await manager.StartAsync();var watch=Stopwatch.StartNew();while(manager.State==ServerState.Starting&&watch.Elapsed.TotalSeconds<15)await Task.Delay(20);Assert(manager.State==ServerState.Running,"Mock did not start");string record=File.ReadAllText(Path.Combine(root,"server-process.json"));await manager.PlayerActionAsync(PlayerAction.Whitelist,target);await manager.PlayerActionAsync(PlayerAction.Operator,target);await manager.PlayerActionAsync(PlayerAction.RemoveOperator,target);await manager.PlayerActionAsync(PlayerAction.Ban,target);await manager.PlayerActionAsync(PlayerAction.Unban,target);await manager.PlayerActionAsync(PlayerAction.RemoveWhitelist,target);manager.ObservePlayerPresence("[12:00:00] [Server thread/INFO]: There are 2 of a max of 8 players online: TestOwner, FriendPlayer");await manager.PlayerActionAsync(PlayerAction.Kick,new(Id(2),"TestOwner"));await manager.TeleportPlayerAsync("TestOwner","FriendPlayer");Assert(File.ReadAllText(Path.Combine(root,"server-process.json"))==record&&manager.State==ServerState.Running,"Player actions restarted server");var commands=File.ReadAllLines(Path.Combine(manager.ServerDir,"mock-commands.log"));Assert(commands.Contains("tp TestOwner FriendPlayer")&&commands.Contains("kick TestOwner"),"Live actions did not send commands");checks.Add("Live permission changes wait for server-owned files; kick and teleport wait for server replies; server stays online");await manager.StopAsync();ServerManager.WriteJson(report,new{passed=true,checks,realServerTouched=false});
        }catch(Exception ex){ServerManager.WriteJson(report,new{passed=false,error=ex.ToString(),checks,realServerTouched=false});}finally{if(manager.HasProcess)await manager.StopAsync();}
    }
    internal static void Ui(string report,bool demo=false)
    {
        report=Path.GetFullPath(report);var root=Path.Combine(Path.GetDirectoryName(report)!,"players-ui-fixture-"+Guid.NewGuid().ToString("N"));Fixture(root,37);ServerManager.WriteJson(Path.Combine(root,"appearance.json"),new AppearanceSettings());using var manager=new ServerManager(root);manager.ObservePlayerPresence("[12:00:00] [Server thread/INFO]: There are 3 of a max of 8 players online: TestOwner, FriendPlayer, Player04");using var form=new MainForm(manager,playersTestReport:demo?"__players_demo__":report);Application.Run(form);
    }
}
public sealed partial class MainForm
{
    internal async Task VerifyPlayersDesign(string report)
    {
        var checks=new List<string>();void Assert(bool pass,string message){if(!pass)throw new Exception(message);}async Task Until(Func<bool> condition){var watch=Stopwatch.StartNew();while(!condition()){if(watch.Elapsed.TotalSeconds>10)throw new TimeoutException("Players UI wait failed");await Task.Delay(20);}}void Capture(string name){using var image=new Bitmap(Width,Height);DrawToBitmap(image,new Rectangle(Point.Empty,Size));image.Save(Path.Combine(Path.GetDirectoryName(report)!,name+".png"));}
        try{
            playerImagesDisabled=true;ShowPage("Players");await Until(()=>playerDataLoaded&&!playerLoadRunning);Assert(managedPlayers.Count==37&&managedPlayers.Count(p=>p.Online)==3,"Player data did not reach UI");
            foreach(var size in new[]{new Size(1320,744),new Size(1160,680)}){ClientSize=new Size(LogicalToDeviceUnits(size.Width),LogicalToDeviceUnits(size.Height));await Task.Delay(50);Assert(playerTable.Bottom<=pages["Players"].Height&&playerRowHost.Bottom<playerPager.Top,"Player table or pager clipped");foreach(var row in playerRowHost.Controls.OfType<PaintedPanel>()){Assert(row.Bottom<=playerRowHost.Height,"Player row clipped");var buttons=row.Controls.OfType<HarborButton>().ToArray();Assert(buttons.All(b=>b.Right<=row.Width)&&buttons.Zip(buttons.Skip(1)).All(p=>p.First.Right<p.Second.Left),"Player actions overlap");foreach(var action in buttons.Where(b=>b.Text is "Teleport" or "Kick")){int text=TextRenderer.MeasureText(action.Text,action.Font,new Size(int.MaxValue,int.MaxValue),TextFormatFlags.SingleLine|TextFormatFlags.NoPadding).Width;Assert(text+2<=action.Width-action.LogicalToDeviceUnits(61),"Player action label clipped");}}Capture(size.Width==1320?"players-list":"players-list-small");}
            Assert(playerNext.Enabled&&!playerPrevious.Enabled,"Pagination initial state wrong");playerNext.PerformClick();Assert(playerPage==1&&playerPrevious.Enabled,"Next page did not move");playerPrevious.PerformClick();Assert(playerPage==0,"Previous page did not return");playerSearch.Text="FriendPlayer";Assert(filteredPlayers.Length==1,"Name search failed");playerSearch.Text=PlayerTests.Id(6);Assert(filteredPlayers.Length==1,"UUID search failed");playerSearch.Clear();SelectPlayerTab("Whitelist");Assert(filteredPlayers.Length==3,"Whitelist filter wrong");SelectPlayerTab("Operators");Assert(filteredPlayers.Length==2,"Operators filter wrong");SelectPlayerTab("Bans");Assert(filteredPlayers.Length==1&&filteredPlayers[0].Banned,"Bans filter wrong");Capture("players-bans");playerSearch.Text="not present";Assert(filteredPlayers.Length==0&&!playerNext.Enabled,"Empty search retained rows");playerSearch.Clear();SelectPlayerTab("Player List");Assert(playerRowHost.Controls.OfType<PaintedPanel>().SelectMany(r=>r.Controls.OfType<HarborButton>()).Where(b=>b.Text is "Teleport" or "Kick").All(b=>!b.Enabled),"Stopped server enabled live actions");checks.Add("Real rows, four summaries, name/UUID search, all tabs, pagination, centered complete action labels, stopped-state gating, and both supported window sizes");ServerManager.WriteJson(report,new{passed=true,checks,realServerTouched=false});
        }catch(Exception ex){ServerManager.WriteJson(report,new{passed=false,error=ex.ToString(),checks,realServerTouched=false});}finally{exiting=true;Close();}
    }
}
