using System.Diagnostics;
using System.IO.Compression;
using System.Reflection;
using System.Security.Cryptography;
using System.Text.Json;
using Microsoft.Win32;
namespace HarborSetup;
internal static class Program
{
    internal static string? TestRoot;
    static string? detectedRoot;
    internal static string InstallRoot=>TestRoot??(detectedRoot??=InstallLocation.Find());
    internal static bool IsInstalled=>File.Exists(Path.Combine(InstallRoot,"Minecraft Harbor.exe"));
    internal static string AppDataRoot=>Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"MinecraftHarbor","Data");
    [STAThread] static int Main(string[] args){try{if(args.Length==2&&args[0]=="--self-test"){Verify(args[1]);return 0;}Application.SetHighDpiMode(HighDpiMode.PerMonitorV2);Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);if(args.Length==2&&args[0]=="--preview"){Application.Run(new SetupForm(args[1]));return 0;}if(args.Length==2&&args[0]=="--uninstall-worker"){try{using var owner=Process.GetProcessById(int.Parse(args[1]));if(!owner.WaitForExit(30000))throw new InvalidOperationException("Close the original uninstall window and retry.");}catch(ArgumentException){}Application.Run(new SetupForm(uninstall:true,worker:true));return 0;}Application.Run(new SetupForm(uninstall:args.Contains("--uninstall")));return 0;}catch(Exception ex){if(args.Length==2)File.WriteAllText(args[1]+".error.txt",ex.ToString());else MessageBox.Show(ex.Message,"Minecraft Harbor Setup");return 1;}}
    static byte[] Payload(){using var stream=Assembly.GetExecutingAssembly().GetManifestResourceStream("Harbor.Payload.zip")!;using var memory=new MemoryStream();stream.CopyTo(memory);byte[] bytes=memory.ToArray();using var hashStream=Assembly.GetExecutingAssembly().GetManifestResourceStream("Harbor.Payload.sha256")!;using var reader=new StreamReader(hashStream);if(Convert.ToHexString(SHA256.HashData(bytes))!=reader.ReadToEnd().Trim())throw new InvalidDataException("Installer payload failed verification.");return bytes;}
    static string SafeTarget(string root,string path){if(path.Length==0||path.Contains('\\')||Path.IsPathRooted(path)||path.Split('/').Any(p=>p is ".." or "."||p.Contains(':')))throw new InvalidDataException("Invalid installer file path.");string resolved=Path.GetFullPath(Path.Combine(root,path));if(!resolved.StartsWith(Path.GetFullPath(root).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("Installer file escapes its folder.");string? cursor=resolved;while(cursor!=null){if((Directory.Exists(cursor)||File.Exists(cursor))&&(File.GetAttributes(cursor)&FileAttributes.ReparsePoint)!=0)throw new InvalidDataException("Install folders cannot be links.");cursor=Path.GetDirectoryName(cursor);}return resolved;}
    internal static string[] Extract(string root,Action<int>? progress=null){using var zip=new ZipArchive(new MemoryStream(Payload()),ZipArchiveMode.Read);var entries=zip.Entries.Where(e=>!e.FullName.EndsWith('/')).ToArray();if(entries.Length==0||entries.Select(e=>e.FullName).Distinct(StringComparer.OrdinalIgnoreCase).Count()!=entries.Length)throw new InvalidDataException("Invalid installer contents.");foreach(var entry in entries)SafeTarget(root,entry.FullName);Directory.CreateDirectory(root);int done=0;foreach(var entry in entries){string target=SafeTarget(root,entry.FullName);Directory.CreateDirectory(Path.GetDirectoryName(target)!);using var input=entry.Open();using var output=File.Create(target);input.CopyTo(output);if(output.Length!=entry.Length)throw new IOException("Incomplete installer file.");progress?.Invoke(++done*100/entries.Length);}return entries.Select(e=>e.FullName).ToArray();}
    static void RequireClosed(string root)=>HarborUpdates.UpdateShutdown.CloseApplication(Path.Combine(root,"Minecraft Harbor.exe"),TimeSpan.FromMinutes(10));
    internal static void Install(bool desktop,Action<int> progress,bool integrate=true){RequireClosed(InstallRoot);string staged=InstallRoot+"-setup-"+Guid.NewGuid().ToString("N");string[] files=Extract(staged,progress);Directory.CreateDirectory(InstallRoot);string recovery=InstallRoot+"-previous-"+Guid.NewGuid().ToString("N");Directory.CreateDirectory(recovery);var copied=new List<string>();try{foreach(string file in files){string destination=SafeTarget(InstallRoot,file);Directory.CreateDirectory(Path.GetDirectoryName(destination)!);if(File.Exists(destination)){string saved=SafeTarget(recovery,file);Directory.CreateDirectory(Path.GetDirectoryName(saved)!);File.Copy(destination,saved);}copied.Add(file);File.Copy(SafeTarget(staged,file),destination,true);}File.Copy(Environment.ProcessPath!,Path.Combine(InstallRoot,"Uninstall Minecraft Harbor.exe"),true);File.WriteAllText(Path.Combine(InstallRoot,"installed-files.json"),JsonSerializer.Serialize(files));if(integrate){Shortcut(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.StartMenu),"Programs","Minecraft Harbor.lnk"));if(desktop)Shortcut(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),"Minecraft Harbor.lnk"));using var key=Registry.CurrentUser.CreateSubKey("Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\MinecraftHarbor");key.SetValue("DisplayName","Minecraft Harbor");key.SetValue("DisplayVersion","1.4.0");key.SetValue("Publisher","Rise Digital");key.SetValue("InstallLocation",InstallRoot);key.SetValue("DisplayIcon",Path.Combine(InstallRoot,"Minecraft Harbor.exe"));key.SetValue("UninstallString","\""+Path.Combine(InstallRoot,"Uninstall Minecraft Harbor.exe")+"\" --uninstall");key.SetValue("NoModify",1);key.SetValue("NoRepair",1);}}catch{foreach(string file in copied){string target=SafeTarget(InstallRoot,file),saved=SafeTarget(recovery,file);if(File.Exists(saved))File.Copy(saved,target,true);else if(File.Exists(target))File.Delete(target);}throw;}finally{CleanKnownFolder(staged);CleanKnownFolder(recovery);}}
    static void Shortcut(string path){Type type=Type.GetTypeFromProgID("WScript.Shell")??throw new IOException("Windows shortcut service unavailable");dynamic shell=Activator.CreateInstance(type)!;try{dynamic link=shell.CreateShortcut(path);try{link.TargetPath=Path.Combine(InstallRoot,"Minecraft Harbor.exe");link.WorkingDirectory=InstallRoot;link.Description="Minecraft Harbor — manage your Minecraft servers";link.IconLocation=link.TargetPath+",0";link.Save();}finally{System.Runtime.InteropServices.Marshal.FinalReleaseComObject(link);}}finally{System.Runtime.InteropServices.Marshal.FinalReleaseComObject(shell);}}
    static void CleanKnownFolder(string root){if(!Directory.Exists(root))return;foreach(string path in Directory.EnumerateFiles(root,"*",SearchOption.AllDirectories)){SafeTarget(root,Path.GetRelativePath(root,path).Replace('\\','/'));File.Delete(path);}foreach(string path in Directory.EnumerateDirectories(root,"*",SearchOption.AllDirectories).OrderByDescending(p=>p.Length))Directory.Delete(path);Directory.Delete(root);}
    internal static void Uninstall(bool integrate=true){RequireClosed(InstallRoot);string manifest=Path.Combine(InstallRoot,"installed-files.json");if(!File.Exists(manifest))throw new InvalidOperationException("The installation record is missing. Your server data has not been touched.");var files=JsonSerializer.Deserialize<string[]>(File.ReadAllText(manifest))??[];foreach(string file in files){string path=SafeTarget(InstallRoot,file);if(File.Exists(path))File.Delete(path);}if(integrate){foreach(string shortcut in new[]{Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.StartMenu),"Programs","Minecraft Harbor.lnk"),Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),"Minecraft Harbor.lnk")})if(File.Exists(shortcut))File.Delete(shortcut);Registry.CurrentUser.DeleteSubKey("Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\MinecraftHarbor",false);}File.Delete(manifest);string uninstaller=SafeTarget(InstallRoot,"Uninstall Minecraft Harbor.exe");if(File.Exists(uninstaller))File.Delete(uninstaller);foreach(string directory in Directory.EnumerateDirectories(InstallRoot,"*",SearchOption.AllDirectories).OrderByDescending(p=>p.Length)){SafeTarget(InstallRoot,Path.GetRelativePath(InstallRoot,directory).Replace('\\','/'));if(!Directory.EnumerateFileSystemEntries(directory).Any())Directory.Delete(directory);}if(!Directory.EnumerateFileSystemEntries(InstallRoot).Any())Directory.Delete(InstallRoot);}
    internal static void StartUninstallWorker(){string temporary=Path.Combine(Path.GetTempPath(),"Minecraft-Harbor-Uninstall-"+Guid.NewGuid().ToString("N")+".exe");File.Copy(Environment.ProcessPath!,temporary);var start=new ProcessStartInfo(temporary){UseShellExecute=true};start.ArgumentList.Add("--uninstall-worker");start.ArgumentList.Add(Environment.ProcessId.ToString());Process.Start(start);}
    static void Verify(string report){string root=Path.Combine(Path.GetDirectoryName(Path.GetFullPath(report))!,"installer-test-"+Guid.NewGuid().ToString("N"));string[] files=Extract(root);if(!files.Contains("Minecraft Harbor.exe")||!files.Contains("client-setup/Minecraft-Harbor-Agent-Setup.exe")||files.Any(f=>f.StartsWith("server/")||f=="settings.json"||f=="library.json"||f.StartsWith("backups/")||f.Contains("minecraftinstance.json")))throw new Exception("Payload is incomplete or includes private server data.");string client=SafeTarget(root,"client-setup/Minecraft-Harbor-Agent-Setup.exe");if(Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(client)))!=File.ReadAllText(client+".sha256").Trim())throw new Exception("Client installer checksum mismatch.");bool rejected=false;try{SafeTarget(root,"../outside");}catch(InvalidDataException){rejected=true;}if(!rejected)throw new Exception("Unsafe payload path accepted.");foreach(string file in files)if(!File.Exists(SafeTarget(root,file)))throw new Exception("Missing extracted file.");try{TestRoot=Path.Combine(root,"installed");Install(false,_=>{},false);string privateFile=Path.Combine(TestRoot,"my-world","level.dat");Directory.CreateDirectory(Path.GetDirectoryName(privateFile)!);File.WriteAllText(privateFile,"keep my save");Install(false,_=>{},false);if(File.ReadAllText(privateFile)!="keep my save")throw new Exception("Update removed user data.");Uninstall(false);if(File.Exists(Path.Combine(TestRoot,"Minecraft Harbor.exe"))||File.ReadAllText(privateFile)!="keep my save")throw new Exception("Uninstaller removed user data or left the app.");}finally{TestRoot=null;}File.WriteAllText(report,JsonSerializer.Serialize(new{passed=true,fileCount=files.Length,payloadVerified=true,installUpdateUninstallPassed=true,userDataPreserved=true,privateServerIncluded=false,shortcutsOrRegistryChanged=false},new JsonSerializerOptions{WriteIndented=true}));}
}
internal sealed class SetupForm:Form
{
    readonly Label heading,message;readonly ProgressBar progress;readonly Button action,cancel;readonly CheckBox desktop;bool busy,installed;readonly bool uninstall;
    internal SetupForm(string? preview=null,bool uninstall=false,bool worker=false){this.uninstall=uninstall;bool updating=!uninstall&&Program.IsInstalled;SuspendLayout();Text=uninstall?"Uninstall Minecraft Harbor":(updating?"Update Minecraft Harbor 1.4":"Minecraft Harbor 1.4 Setup");ClientSize=new(620,370);BackColor=Color.FromArgb(13,23,33);ForeColor=Color.FromArgb(239,246,252);Font=new("Segoe UI",11);StartPosition=FormStartPosition.CenterScreen;FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;Icon=Icon.ExtractAssociatedIcon(Environment.ProcessPath!);heading=new(){Text=uninstall?"Uninstall Minecraft Harbor":updating?"Update Minecraft Harbor":"Minecraft Harbor 1.4",Font=new("Segoe UI",24,FontStyle.Bold),Bounds=new(28,28,565,55)};message=new(){Text=uninstall?"Remove Harbor and its shortcuts. Your worlds, servers, and backups will be kept.":updating?"Update to version 1.4.":"Install Minecraft Harbor 1.4.",Bounds=new(30,104,560,95),ForeColor=Color.FromArgb(175,193,215)};desktop=new(){Text="Create a desktop shortcut",Checked=true,Bounds=new(30,213,540,30),Visible=!uninstall};progress=new(){Bounds=new(30,257,560,13),Visible=false};action=Button(uninstall?"Uninstall":updating?"Update Harbor":"Install Harbor",330,294,260,true);cancel=Button("Cancel",30,294,280,false);Controls.AddRange([heading,message,desktop,progress,action,cancel]);cancel.Click+=(_,_)=>Close();action.Click+=async(_,_)=>{if(installed){if(!uninstall)Process.Start(new ProcessStartInfo(Path.Combine(Program.InstallRoot,"Minecraft Harbor.exe")){UseShellExecute=true});Close();return;}if(uninstall&&!worker){try{Program.StartUninstallWorker();Close();}catch(Exception ex){message.Text=ex.Message;}return;}busy=true;message.Text=uninstall?"Closing Harbor…":updating?"Closing Harbor and updating…":"Installing…";action.Enabled=cancel.Enabled=desktop.Enabled=false;progress.Visible=true;bool shortcut=desktop.Checked;try{if(uninstall)await Task.Run(()=>Program.Uninstall());else await Task.Run(()=>Program.Install(shortcut,n=>BeginInvoke(()=>progress.Value=n)));installed=true;heading.Text=uninstall?"Harbor removed":updating?"Harbor updated.":"Ready to host.";message.Text=uninstall?"Your server data and backups have been kept.":updating?"Update complete.":"Installation complete.";action.Text=uninstall?"Finish":"Open Harbor";cancel.Text="Close";progress.Value=100;}catch(Exception ex){File.AppendAllText(Path.Combine(Path.GetTempPath(),"MinecraftHarbor-setup.log"),DateTime.UtcNow.ToString("O")+" "+ex+Environment.NewLine);message.Text=ex.Message;}finally{busy=false;action.Enabled=cancel.Enabled=true;desktop.Enabled=!installed;}};FormClosing+=(_,e)=>e.Cancel=busy;Shown+=(_,_)=>{if(worker){action.PerformClick();return;}if(preview!=null){using var image=new Bitmap(Width,Height);DrawToBitmap(image,new(Point.Empty,Size));image.Save(preview);Close();}};AutoScaleDimensions=new(96,96);AutoScaleMode=AutoScaleMode.Dpi;ResumeLayout(true);}
    Button Button(string text,int x,int y,int width,bool primary){var b=new Button{Text=text,Bounds=new(x,y,width,46),TextAlign=ContentAlignment.MiddleCenter,UseMnemonic=false,FlatStyle=FlatStyle.Flat,BackColor=primary?Color.FromArgb(37,207,119):Color.FromArgb(24,43,59),ForeColor=ForeColor,Font=new("Segoe UI",11,FontStyle.Bold)};b.FlatAppearance.BorderColor=Color.FromArgb(55,94,121);return b;}
}




